// Code generated by mss application template v1.3.6. DO NOT EDIT.
package main

import (
	"context"
	"log"

	adminapp "github.com/mss-boot-io/mss-boot-admin/admin/app"
	"github.com/shop-r1/mss-shop/apps/tenant-platform/internal/modules"
)

func main() {
	if err := adminapp.ExecuteContext(
		context.Background(),
		adminapp.WithBusinessModules(modules.Modules()...),
	); err != nil {
		log.Fatal(err)
	}
}
