export const LEGACY_DOMAINS = [
  'catalog',
  'customers',
  'orders',
  'fulfillment',
  'marketing',
  'finance',
  'sales',
  'messaging',
  'inventory',
  'settings',
  'storefront',
] as const;

export type LegacyDomain = (typeof LEGACY_DOMAINS)[number];

export interface LegacyResourceCatalogEntry<
  Domain extends LegacyDomain = LegacyDomain,
  Resource extends string = string,
> {
  readonly domain: Domain;
  readonly resource: Resource;
  readonly path: `/business/${Domain}/${Resource}`;
  readonly menuName: `legacy.${Domain}.${Resource}`;
  readonly titleKey: `legacy.resource.${Resource}.title`;
  readonly domainTitleKey: `legacy.domain.${Domain}`;
  readonly routePermission: `/business/${Domain}/${Resource}`;
  readonly listPermission: `/business/${Domain}/${Resource}/permissions/list`;
  readonly readPermission: `/business/${Domain}/${Resource}/permissions/read`;
  readonly createPermission: `/business/${Domain}/${Resource}/permissions/create`;
  readonly updatePermission: `/business/${Domain}/${Resource}/permissions/update`;
  readonly deletePermission: `/business/${Domain}/${Resource}/permissions/delete`;
}

function resource<const Domain extends LegacyDomain, const Resource extends string>(
  domain: Domain,
  name: Resource,
): LegacyResourceCatalogEntry<Domain, Resource> {
  return {
    domain,
    resource: name,
    path: `/business/${domain}/${name}`,
    menuName: `legacy.${domain}.${name}`,
    titleKey: `legacy.resource.${name}.title`,
    domainTitleKey: `legacy.domain.${domain}`,
    routePermission: `/business/${domain}/${name}`,
    listPermission: `/business/${domain}/${name}/permissions/list`,
    readPermission: `/business/${domain}/${name}/permissions/read`,
    createPermission: `/business/${domain}/${name}/permissions/create`,
    updatePermission: `/business/${domain}/${name}/permissions/update`,
    deletePermission: `/business/${domain}/${name}/permissions/delete`,
  };
}

/**
 * The 50 mall-owned tables from the qualified legacy compatibility inventory.
 * Seven product/logistics resources are per-tenant snapshots in the fixed
 * business schema. Every resource remains read-only at this checkpoint.
 * This is a navigation and API allowlist, never a client-selected SQL table list.
 */
export const LEGACY_RESOURCES = [
  resource('catalog', 'brands'),
  resource('catalog', 'categories'),
  resource('catalog', 'classes'),
  resource('catalog', 'goods_infos'),
  resource('catalog', 'goods'),
  resource('catalog', 'goods_assembles'),
  resource('catalog', 'goods_shipping_warehouses'),
  resource('catalog', 'goods_specifications'),
  resource('catalog', 'member_goods'),
  resource('catalog', 'show_categories'),

  resource('customers', 'members'),
  resource('customers', 'consumers'),
  resource('customers', 'consignees'),
  resource('customers', 'senders'),
  resource('customers', 'member_levels'),
  resource('customers', 'collections'),

  resource('orders', 'orders'),
  resource('orders', 'payment_orders'),
  resource('orders', 'order_unit_packs'),
  resource('orders', 'order_goods'),

  resource('fulfillment', 'shipping_warehouses'),
  resource('fulfillment', 'couriers'),
  resource('fulfillment', 'courier_pack_rules'),
  resource('fulfillment', 'courier_links'),
  resource('fulfillment', 'courier_installs'),
  resource('fulfillment', 'courier_templates'),
  resource('fulfillment', 'payment_installs'),

  resource('marketing', 'activities'),
  resource('marketing', 'activity_links'),
  resource('marketing', 'coupons'),
  resource('marketing', 'coupon_links'),
  resource('marketing', 'coupon_parents'),
  resource('marketing', 'function_circles'),

  resource('finance', 'finances'),
  resource('finance', 'finance_logs'),
  resource('finance', 'gold_withdraws'),

  resource('sales', 'sells'),
  resource('sales', 'sell_goods'),

  resource('messaging', 'messages'),
  resource('messaging', 'message_users'),
  resource('messaging', 'message_events'),
  resource('messaging', 'message_templates'),

  resource('inventory', 'real_warehouses'),
  resource('inventory', 'inventories'),
  resource('inventory', 'inventory_tracks'),
  resource('inventory', 'receipts'),
  resource('inventory', 'receipt_goods'),
  resource('inventory', 'inventory_checks'),

  resource('settings', 'system_configs'),
  resource('storefront', 'shopping_carts'),
] as const;

export type LegacyResourceName = (typeof LEGACY_RESOURCES)[number]['resource'];
export type LegacyResourceEntry = (typeof LEGACY_RESOURCES)[number];

/**
 * Every non-secret field exposed by the reviewed mall backend manifest.
 * Backend descriptors emit these names as legacy.fields.<name> message keys.
 * The catalog is intentionally explicit so locale completeness can be checked
 * against the backend allowlist without making the runtime bundle read Go
 * source files.
 */
export const LEGACY_FIELDS = [
  'activities_data',
  'activities_data_copy',
  'activity_id',
  'activity_type',
  'address',
  'album',
  'alias',
  'amount',
  'app',
  'attributes',
  'aud_to_cny',
  'aud_to_cny_copy',
  'bank_location',
  'bank_type',
  'bar_code',
  'bg_color',
  'bg_image',
  'bg_img',
  'bill',
  'bill_account',
  'bill_create_time',
  'bill_date',
  'brand_id',
  'buy_num',
  'category_id',
  'change',
  'change_aud',
  'change_courier',
  'channel',
  'check_status',
  'city',
  'click_num',
  'code_data',
  'commission_rmb',
  'consignee_data',
  'consignee_id',
  'consumer_id',
  'contact_qr_code',
  'content',
  'continued_price',
  'count',
  'country',
  'coupon_id',
  'courier_id',
  'courier_install_id',
  'courier_logo',
  'courier_name',
  'courier_no',
  'courier_price',
  'courier_price_copy',
  'couriers_data',
  'created_at',
  'created_by',
  'created_by_name',
  'currency',
  'custom_courier_fee_data',
  'custom_pay',
  'custom_price',
  'default',
  'default_select',
  'deleted_at',
  'description',
  'details_data',
  'end_at',
  'enough_price',
  'enough_type',
  'event',
  'event_id',
  'expiration',
  'extend_data',
  'extend_multi',
  'external_order_id',
  'finance_type',
  'financial_audit',
  'financial_id',
  'financial_name',
  'financial_remark',
  'first_price',
  'first_weight',
  'free_shipping',
  'freeze',
  'freeze_aud',
  'freeze_gold',
  'freeze_overage',
  'freeze_overage_aud',
  'from_type',
  'get_self',
  'gold',
  'goods_data',
  'goods_id',
  'goods_info_id',
  'goods_name',
  'goods_price',
  'goods_price_copy',
  'goods_spec_id',
  'goods_specification_data',
  'goods_specification_id',
  'goods_type',
  'has_market',
  'has_pack_rule',
  'has_specification',
  'head_image',
  'head_image_url',
  'hits',
  'id',
  'image',
  'img',
  'index_img',
  'init',
  'inventory',
  'keywords',
  'left_rule_id',
  'level',
  'level_id',
  'link_id',
  'link_type',
  'links_data',
  'logo',
  'max_amount',
  'max_weight',
  'media',
  'member_id',
  'member_ids_data',
  'member_level_ids_data',
  'member_level_price_data',
  'member_name',
  'message_id',
  'metadata',
  'method',
  'mixed',
  'mixed_sum',
  'money',
  'money_copy',
  'name',
  'name_en',
  'name_zh',
  'need_id_card',
  'need_inventory',
  'need_update_weight',
  'net_weight',
  'nickname',
  'object',
  'object_ids_data',
  'old',
  'old_aud',
  'open_id',
  'order_create_time',
  'order_fee',
  'order_id',
  'order_pay_id',
  'order_status',
  'order_status_copy',
  'overage',
  'overage_aud',
  'pack_data',
  'pack_rule',
  'pack_specification',
  'paid',
  'parent_category_id',
  'parent_id',
  'parent_referrer_id',
  'parent_show_category_id',
  'pay_qr_code',
  'pay_url',
  'payment',
  'payment_account',
  'payment_id',
  'payment_ids',
  'payment_install_id',
  'payment_name',
  'payment_order_id',
  'payment_status',
  'payment_time',
  'percent_level0',
  'percent_level1',
  'phone',
  'prefix',
  'price',
  'price_copy',
  'price_total',
  'price_unit',
  'print',
  'province',
  'quality_period',
  'quantity',
  'quantity_change',
  'ratio',
  'read',
  'read_time',
  'real_fee',
  'real_name',
  'real_warehouse_id',
  'receipt_id',
  'redirect',
  'reduce',
  'reduce_fee',
  'reduce_fee_copy',
  'referral_code',
  'referrer_id',
  'region',
  'remark',
  'selected',
  'sell_id',
  'seller_id',
  'send_status',
  'send_type',
  'sender_data',
  'sender_id',
  'sent',
  'sex',
  'shipping_warehouse_id',
  'shop_name',
  'show',
  'show_category_id',
  'simple',
  'site_url',
  'sort',
  'specification',
  'specification_info',
  'stage',
  'start_at',
  'status',
  'supplier',
  'tag',
  'tenant_id',
  'title',
  'top',
  'topped_at',
  'type',
  'union_id',
  'unit',
  'unit_price',
  'updated_at',
  'url',
  'use',
  'use_self_aud_to_cny',
  'used',
  'user_id',
  'username',
  'video',
  'voucher_image',
  'voucher_image_copy',
  'warehouse_id',
  'warehouse_ids_data',
  'weight',
] as const;

export type LegacyFieldName = (typeof LEGACY_FIELDS)[number];

const resourcesByPath = new Map<string, LegacyResourceEntry>(
  LEGACY_RESOURCES.map((entry) => [entry.path, entry]),
);

const resourcesByName = new Map<string, LegacyResourceEntry>(
  LEGACY_RESOURCES.map((entry) => [entry.resource, entry]),
);

export function findLegacyResourceByPath(pathname: string): LegacyResourceEntry | undefined {
  const normalized = pathname.length > 1 ? pathname.replace(/\/+$/, '') : pathname;
  return resourcesByPath.get(normalized);
}

export function findLegacyResourceByName(name: string): LegacyResourceEntry | undefined {
  return resourcesByName.get(name);
}
