// Code generated by mss application template v1.3.6. DO NOT EDIT.

import type { AdminBusinessRoute } from '@mss-boot-io/admin-web/business';
import customBusinessRoutes from '../src/business/routes.config';
import generatedBusinessRoutes from './business-routes.generated';

const businessRoutes: AdminBusinessRoute[] = [...generatedBusinessRoutes, ...customBusinessRoutes];

export default businessRoutes;
