// Code generated by mss module template 1.3.0-frontend-v6.6 sync. DO NOT EDIT.

export default [
  {
    path: "/legacy-migration-checkpoints",
    name: "legacycheckpoint",
    icon: "table",
    component: "./generated/LegacyMigrationCheckpoint",
    access: 'canAccessRoute',
    permission: "/legacy-migration-checkpoints",
  },
];
