// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/mss-boot-io/mss-boot-admin/admin/models"
	adminpkg "github.com/mss-boot-io/mss-boot-admin/admin/pkg"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/enum"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const LegacyMigrationCheckpointAuthorizationMigrationID migration.MigrationID = "20260901110001"

const (
	legacycheckpointAuthorizationScopeRole   = "role"
	legacycheckpointAuthorizationScopeGlobal = "global"
	legacycheckpointAuthorizationResource    = "authorization"
)

type legacycheckpointPermissionSeed struct {
	code          string
	displayName   string
	componentPath string
	defaultRoles  []string
}

var legacycheckpointPermissionSeeds = []legacycheckpointPermissionSeed{
	{
		code:          PermissionCreate,
		displayName:   "新建存量迁移检查点",
		componentPath: "/legacy-migration-checkpoints/permissions/create",
		defaultRoles:  []string{"admin"},
	},
	{
		code:          PermissionDelete,
		displayName:   "删除存量迁移检查点",
		componentPath: "/legacy-migration-checkpoints/permissions/delete",
		defaultRoles:  []string{"admin"},
	},
	{
		code:          PermissionExport,
		displayName:   "导出存量迁移检查点",
		componentPath: "/legacy-migration-checkpoints/permissions/export",
		defaultRoles:  []string{"admin"},
	},
	{
		code:          PermissionList,
		displayName:   "查看存量迁移检查点列表",
		componentPath: "/legacy-migration-checkpoints/permissions/list",
		defaultRoles:  []string{"admin"},
	},
	{
		code:          PermissionRead,
		displayName:   "查看存量迁移检查点",
		componentPath: "/legacy-migration-checkpoints/permissions/read",
		defaultRoles:  []string{"admin"},
	},
	{
		code:          PermissionUpdate,
		displayName:   "更新存量迁移检查点",
		componentPath: "/legacy-migration-checkpoints/permissions/update",
		defaultRoles:  []string{"admin"},
	},
}

type legacycheckpointOperationAuthorizationSeed struct {
	name          string
	method        string
	path          string
	permission    string
	componentPath string
	defaultRoles  []string
}

var legacycheckpointOperationAuthorizationSeeds = []legacycheckpointOperationAuthorizationSeed{
	{
		name:          "api.legacycheckpoint.create",
		method:        "POST",
		path:          "/admin/api/legacy-migration-checkpoints",
		permission:    PermissionCreate,
		componentPath: "/legacy-migration-checkpoints/permissions/create",
		defaultRoles:  []string{"admin"},
	},
	{
		name:          "api.legacycheckpoint.delete",
		method:        "DELETE",
		path:          "/admin/api/legacy-migration-checkpoints/:id",
		permission:    PermissionDelete,
		componentPath: "/legacy-migration-checkpoints/permissions/delete",
		defaultRoles:  []string{"admin"},
	},
	{
		name:          "api.legacycheckpoint.export",
		method:        "GET",
		path:          "/admin/api/legacy-migration-checkpoints/export",
		permission:    PermissionExport,
		componentPath: "/legacy-migration-checkpoints/permissions/export",
		defaultRoles:  []string{"admin"},
	},
	{
		name:          "api.legacycheckpoint.get",
		method:        "GET",
		path:          "/admin/api/legacy-migration-checkpoints/:id",
		permission:    PermissionRead,
		componentPath: "/legacy-migration-checkpoints/permissions/read",
		defaultRoles:  []string{"admin"},
	},
	{
		name:          "api.legacycheckpoint.list",
		method:        "GET",
		path:          "/admin/api/legacy-migration-checkpoints",
		permission:    PermissionList,
		componentPath: "/legacy-migration-checkpoints/permissions/list",
		defaultRoles:  []string{"admin"},
	},
	{
		name:          "api.legacycheckpoint.update",
		method:        "PUT",
		path:          "/admin/api/legacy-migration-checkpoints/:id",
		permission:    PermissionUpdate,
		componentPath: "/legacy-migration-checkpoints/permissions/update",
		defaultRoles:  []string{"admin"},
	},
}

func migrateLegacyMigrationCheckpointAuthorization(db *gorm.DB, version string) error {
	return applyLegacyMigrationCheckpointAuthorizationMigration(db, version, nil)
}

// applyLegacyMigrationCheckpointAuthorizationMigration projects permission metadata,
// default-role grants, menu metadata, and durable policy revisions in one
// transaction. The hook exists only for deterministic rollback tests.
func applyLegacyMigrationCheckpointAuthorizationMigration(
	db *gorm.DB,
	version string,
	afterPolicies func() error,
) error {
	if db == nil {
		return errors.New("legacycheckpoint authorization migration database is required")
	}
	if version != LegacyMigrationCheckpointAuthorizationMigrationID.String() {
		return errors.New("legacycheckpoint authorization migration version mismatch")
	}

	return db.Transaction(func(tx *gorm.DB) error {
		var applied int64
		if err := tx.Model(&migrationmodels.Migration{}).
			Where("version = ?", version).
			Count(&applied).Error; err != nil {
			return fmt.Errorf("legacycheckpoint authorization migration: check version: %w", err)
		}
		if applied > 0 {
			return nil
		}

		roles := make(map[string]*models.Role, 1)
		for _, roleName := range []string{"admin"} {
			role, err := resolveLegacyMigrationCheckpointAuthorizationRole(tx, roleName)
			if err != nil {
				return err
			}
			roles[roleName] = role
		}

		parent, err := ensureLegacyMigrationCheckpointAuthorizationParent(
			tx,
			"",
			"",
		)
		if err != nil {
			return err
		}
		parentID := ""
		if parent != nil {
			parentID = parent.ID
		}
		menu, err := upsertLegacyMigrationCheckpointAuthorizationMenu(tx, legacycheckpointAuthorizationMenuSeed{
			name:       "legacycheckpoint",
			path:       "/legacy-migration-checkpoints",
			method:     "GET",
			parentID:   parentID,
			accessType: adminpkg.MenuAccessType,
			permission: "legacycheckpoint:list",
			icon:       "table",
			sort:       0,
			hidden:     false,
		})
		if err != nil {
			return err
		}
		if parent != nil {
			if err := seedLegacyMigrationCheckpointAuthorizationRule(tx, roles["admin"].ID, parent.Type, parent.Path, "GET"); err != nil {
				return err
			}
		}
		if err := seedLegacyMigrationCheckpointAuthorizationRule(tx, roles["admin"].ID, adminpkg.MenuAccessType, menu.Path, "GET"); err != nil {
			return err
		}

		components := make(map[string]*models.Menu, len(legacycheckpointPermissionSeeds))
		for _, seed := range legacycheckpointPermissionSeeds {
			component, err := upsertLegacyMigrationCheckpointAuthorizationMenu(tx, legacycheckpointAuthorizationMenuSeed{
				name:       seed.displayName,
				path:       seed.componentPath,
				method:     "GET",
				parentID:   menu.ID,
				accessType: adminpkg.ComponentAccessType,
				permission: seed.code,
				hidden:     true,
			})
			if err != nil {
				return err
			}
			components[seed.componentPath] = component
			for _, roleName := range seed.defaultRoles {
				if err := seedLegacyMigrationCheckpointAuthorizationRule(tx, roles[roleName].ID, adminpkg.ComponentAccessType, component.Path, "GET"); err != nil {
					return err
				}
			}
		}

		for _, seed := range legacycheckpointOperationAuthorizationSeeds {
			component := components[seed.componentPath]
			if component == nil {
				return fmt.Errorf("legacycheckpoint authorization migration: permission component %q is missing", seed.componentPath)
			}
			if _, err := upsertLegacyMigrationCheckpointAuthorizationMenu(tx, legacycheckpointAuthorizationMenuSeed{
				name:       seed.name,
				path:       seed.path,
				method:     seed.method,
				parentID:   component.ID,
				accessType: adminpkg.APIAccessType,
				permission: seed.permission,
				hidden:     true,
			}); err != nil {
				return err
			}
			for _, roleName := range seed.defaultRoles {
				if err := seedLegacyMigrationCheckpointAuthorizationRule(tx, roles[roleName].ID, adminpkg.APIAccessType, seed.path, seed.method); err != nil {
					return err
				}
			}
		}

		if afterPolicies != nil {
			if err := afterPolicies(); err != nil {
				return fmt.Errorf("legacycheckpoint authorization migration interrupted after policy seed: %w", err)
			}
		}

		for _, roleName := range []string{"admin"} {
			if err := advanceLegacyMigrationCheckpointAuthorizationRevision(tx, legacycheckpointAuthorizationScopeRole, roles[roleName].ID); err != nil {
				return err
			}
		}
		if err := advanceLegacyMigrationCheckpointAuthorizationRevision(tx, legacycheckpointAuthorizationScopeGlobal, ""); err != nil {
			return err
		}

		versionRow := &migrationmodels.Migration{}
		versionRow.SetVersion(version)
		if err := tx.Clauses(clause.OnConflict{
			Columns: []clause.Column{
				{Name: "version"},
			},
			DoNothing: true,
		}).Create(versionRow).Error; err != nil {
			return fmt.Errorf("legacycheckpoint authorization migration: record version: %w", err)
		}
		return nil
	})
}

func resolveLegacyMigrationCheckpointAuthorizationRole(tx *gorm.DB, name string) (*models.Role, error) {
	var matches []models.Role
	if err := tx.Unscoped().Where("name = ?", name).Order("id").Limit(2).Find(&matches).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: resolve role %q: %w", name, err)
	}
	if len(matches) > 1 {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: role %q is ambiguous", name)
	}
	if len(matches) == 1 {
		role := &matches[0]
		if role.DeletedAt.Valid || role.Status != enum.Enabled {
			return nil, fmt.Errorf("legacycheckpoint authorization migration: role %q is not active", name)
		}
		return role, nil
	}
	role := &models.Role{
		Name:   name,
		Status: enum.Enabled,
		Remark: "generated legacycheckpoint default role",
	}
	if err := tx.Create(role).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: create role %q: %w", name, err)
	}
	return role, nil
}

type legacycheckpointAuthorizationMenuSeed struct {
	name       string
	path       string
	method     string
	parentID   string
	accessType adminpkg.AccessType
	permission string
	icon       string
	sort       int
	hidden     bool
}

func ensureLegacyMigrationCheckpointAuthorizationParent(tx *gorm.DB, path string, icon string) (*models.Menu, error) {
	if strings.TrimSpace(path) == "" {
		return nil, nil
	}
	var matches []models.Menu
	if err := tx.Unscoped().
		Where("path = ? AND type IN ?", path, []adminpkg.AccessType{adminpkg.DirectoryAccessType, adminpkg.MenuAccessType}).
		Order("id").
		Limit(2).
		Find(&matches).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: resolve parent %q: %w", path, err)
	}
	if len(matches) > 1 {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: parent %q is ambiguous", path)
	}
	if len(matches) == 1 {
		parent := &matches[0]
		if parent.DeletedAt.Valid || parent.Status != enum.Enabled {
			return nil, fmt.Errorf("legacycheckpoint authorization migration: parent %q is not active", path)
		}
		if normalizedIcon := strings.TrimSpace(icon); normalizedIcon != "" && parent.Icon != normalizedIcon {
			if err := tx.Model(parent).Update("icon", normalizedIcon).Error; err != nil {
				return nil, fmt.Errorf("legacycheckpoint authorization migration: update parent %q icon: %w", path, err)
			}
			parent.Icon = normalizedIcon
		}
		return parent, nil
	}
	parent := &models.Menu{
		Name:   "",
		Path:   path,
		Icon:   strings.TrimSpace(icon),
		Method: "GET",
		Type:   adminpkg.DirectoryAccessType,
		Status: enum.Enabled,
	}
	if err := tx.Create(parent).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: create parent %q: %w", path, err)
	}
	return parent, nil
}

func upsertLegacyMigrationCheckpointAuthorizationMenu(
	tx *gorm.DB,
	seed legacycheckpointAuthorizationMenuSeed,
) (*models.Menu, error) {
	query := tx.Unscoped().Where("type = ? AND path = ?", seed.accessType, seed.path)
	if seed.accessType == adminpkg.APIAccessType {
		query = query.Where("method = ?", seed.method)
	}
	var matches []models.Menu
	if err := query.Order("id").Limit(2).Find(&matches).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: resolve %s %q: %w", seed.accessType, seed.path, err)
	}
	if len(matches) > 1 {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: %s %q is ambiguous", seed.accessType, seed.path)
	}
	if len(matches) == 0 {
		menu := &models.Menu{
			Name:       seed.name,
			Path:       seed.path,
			Method:     seed.method,
			ParentID:   seed.parentID,
			Icon:       seed.icon,
			Type:       seed.accessType,
			Permission: seed.permission,
			Status:     enum.Enabled,
			Sort:       seed.sort,
			HideInMenu: seed.hidden,
		}
		if err := tx.Create(menu).Error; err != nil {
			return nil, fmt.Errorf("legacycheckpoint authorization migration: create %s %q: %w", seed.accessType, seed.path, err)
		}
		return menu, nil
	}
	menu := &matches[0]
	if menu.DeletedAt.Valid {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: %s %q is soft-deleted", seed.accessType, seed.path)
	}
	if err := tx.Model(menu).Updates(map[string]any{
		"name":         seed.name,
		"method":       seed.method,
		"parent_id":    seed.parentID,
		"icon":         seed.icon,
		"permission":   seed.permission,
		"status":       enum.Enabled,
		"sort":         seed.sort,
		"hide_in_menu": seed.hidden,
	}).Error; err != nil {
		return nil, fmt.Errorf("legacycheckpoint authorization migration: update %s %q: %w", seed.accessType, seed.path, err)
	}
	return menu, nil
}

func seedLegacyMigrationCheckpointAuthorizationRule(
	tx *gorm.DB,
	roleID string,
	accessType adminpkg.AccessType,
	path string,
	method string,
) error {
	if strings.TrimSpace(roleID) == "" {
		return errors.New("legacycheckpoint authorization migration: role ID is empty")
	}
	rule := &models.CasbinRule{
		PType: "p",
		V0:    roleID,
		V1:    accessType.String(),
		V2:    path,
		V3:    method,
	}
	if err := tx.Where(
		"ptype = ? AND v0 = ? AND v1 = ? AND v2 = ? AND v3 = ?",
		rule.PType,
		rule.V0,
		rule.V1,
		rule.V2,
		rule.V3,
	).FirstOrCreate(rule).Error; err != nil {
		return fmt.Errorf("legacycheckpoint authorization migration: seed %s %s %s: %w", accessType, method, path, err)
	}
	return nil
}

func advanceLegacyMigrationCheckpointAuthorizationRevision(tx *gorm.DB, scope, ownerID string) error {
	key := &models.ConfigRevision{
		Scope:     scope,
		OwnerID:   ownerID,
		Resource:  legacycheckpointAuthorizationResource,
		Revision:  0,
		UpdatedAt: time.Now(),
	}
	if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(key).Error; err != nil {
		return fmt.Errorf("legacycheckpoint authorization migration: ensure revision %s/%s: %w", scope, ownerID, err)
	}
	var current models.ConfigRevision
	if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).Where(
		"scope = ? AND owner_id = ? AND resource = ?",
		scope,
		ownerID,
		legacycheckpointAuthorizationResource,
	).Take(&current).Error; err != nil {
		return fmt.Errorf("legacycheckpoint authorization migration: lock revision %s/%s: %w", scope, ownerID, err)
	}
	if current.Revision < 0 || current.Revision == 1<<63-1 {
		return fmt.Errorf("legacycheckpoint authorization migration: revision cannot advance for %s/%s", scope, ownerID)
	}
	result := tx.Model(&models.ConfigRevision{}).Where(
		"scope = ? AND owner_id = ? AND resource = ? AND revision = ?",
		scope,
		ownerID,
		legacycheckpointAuthorizationResource,
		current.Revision,
	).Updates(map[string]any{
		"revision":   current.Revision + 1,
		"updated_at": time.Now(),
	})
	if result.Error != nil {
		return fmt.Errorf("legacycheckpoint authorization migration: advance revision %s/%s: %w", scope, ownerID, result.Error)
	}
	if result.RowsAffected != 1 {
		return fmt.Errorf("legacycheckpoint authorization migration: revision changed concurrently for %s/%s", scope, ownerID)
	}
	return nil
}
