// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"github.com/mss-boot-io/mss-boot-admin/admin/business"
)

// Descriptor returns this module's immutable metadata projection.
func Descriptor() business.Descriptor {
	return business.Descriptor{
		Name:        "legacycheckpoint",
		DisplayName: "存量迁移检查点",
		Description: "记录可复核的实施与验收检查点，不保存存量业务数据，也不替代运行时就绪检查。",
		Version:     "v1alpha1",
		Model:       new(LegacyMigrationCheckpoint),
		Permissions: []business.Permission{
			{
				Code:         "legacycheckpoint:create",
				DisplayName:  "新建存量迁移检查点",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "legacycheckpoint:delete",
				DisplayName:  "删除存量迁移检查点",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "legacycheckpoint:export",
				DisplayName:  "导出存量迁移检查点",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "legacycheckpoint:list",
				DisplayName:  "查看存量迁移检查点列表",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "legacycheckpoint:read",
				DisplayName:  "查看存量迁移检查点",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "legacycheckpoint:update",
				DisplayName:  "更新存量迁移检查点",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
		},
		Menu: business.Menu{
			Path:          "/legacy-migration-checkpoints",
			DisplayName:   "存量迁移检查点",
			DisplayNameEn: "Legacy migration checkpoints",
			Icon:          "table",
			Parent:        "",
			Order:         0,
			Hidden:        false,
		},
	}
}
