// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"fmt"
	"regexp"
	"strings"
	"unicode/utf8"
)

// ValidationError is a value-redacted, field-specific input failure.
type ValidationError struct {
	Field string `json:"field"`
	Rule  string `json:"rule"`
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("invalid %s: %s", e.Field, e.Rule)
}

// CreateLegacyMigrationCheckpointInput is the authoritative create contract.
type CreateLegacyMigrationCheckpointInput struct {
	Resource        string `json:"resource"`
	Owner           string `json:"owner"`
	State           string `json:"state"`
	Evidence        string `json:"evidence"`
	ReleaseBlocking *bool  `json:"releaseBlocking"`
}

// UpdateLegacyMigrationCheckpointInput is a presence-aware partial update contract.
type UpdateLegacyMigrationCheckpointInput struct {
	Resource        *string `json:"resource"`
	Owner           *string `json:"owner"`
	State           *string `json:"state"`
	Evidence        *string `json:"evidence"`
	ReleaseBlocking *bool   `json:"releaseBlocking"`
}

// ListLegacyMigrationCheckpointQuery defines bounded filtering, searching, sorting, and paging.
type ListLegacyMigrationCheckpointQuery struct {
	Q               string `form:"q" query:"q"`
	Current         int    `form:"current" query:"current"`
	PageSize        int    `form:"pageSize" query:"pageSize"`
	SortBy          string `form:"sortBy" query:"sortBy"`
	SortOrder       string `form:"sortOrder" query:"sortOrder"`
	Owner           string `form:"owner" query:"owner"`
	State           string `form:"state" query:"state"`
	ReleaseBlocking *bool  `form:"releaseBlocking" query:"releaseBlocking"`
}

// LegacyMigrationCheckpointPage is the stable list response contract.
type LegacyMigrationCheckpointPage struct {
	Data     []LegacyMigrationCheckpoint `json:"data"`
	Total    int64                       `json:"total"`
	Current  int                         `json:"current"`
	PageSize int                         `json:"pageSize"`
}

func (input *CreateLegacyMigrationCheckpointInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	input.Resource = strings.TrimSpace(input.Resource)
	if err := validateResource(input.Resource, true); err != nil {
		return err
	}
	input.Owner = strings.TrimSpace(input.Owner)
	if err := validateOwner(input.Owner, true); err != nil {
		return err
	}
	input.State = strings.TrimSpace(input.State)
	if input.State == "" {
		input.State = "inventoried"
	}
	if err := validateState(input.State, true); err != nil {
		return err
	}
	input.Evidence = strings.TrimSpace(input.Evidence)
	if err := validateEvidence(input.Evidence, false); err != nil {
		return err
	}
	if input.ReleaseBlocking == nil {
		value := true
		input.ReleaseBlocking = &value
	}
	if input.ReleaseBlocking == nil {
		return &ValidationError{Field: "releaseBlocking", Rule: "required"}
	}
	return nil
}

func (input *UpdateLegacyMigrationCheckpointInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	changed := false
	if input.Resource != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Resource)
		input.Resource = &normalized
		if err := validateResource(normalized, true); err != nil {
			return err
		}
	}
	if input.Owner != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Owner)
		input.Owner = &normalized
		if err := validateOwner(normalized, true); err != nil {
			return err
		}
	}
	if input.State != nil {
		changed = true
		normalized := strings.TrimSpace(*input.State)
		input.State = &normalized
		if err := validateState(normalized, true); err != nil {
			return err
		}
	}
	if input.Evidence != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Evidence)
		input.Evidence = &normalized
		if err := validateEvidence(normalized, false); err != nil {
			return err
		}
	}
	if input.ReleaseBlocking != nil {
		changed = true
	}
	if !changed {
		return &ValidationError{Field: "body", Rule: "at-least-one-field"}
	}
	return nil
}

func (query *ListLegacyMigrationCheckpointQuery) normalizeAndValidate() error {
	if query == nil {
		return &ValidationError{Field: "query", Rule: "required"}
	}
	query.Q = strings.TrimSpace(query.Q)
	if query.Current <= 0 {
		query.Current = 1
	}
	if query.PageSize <= 0 {
		query.PageSize = 20
	}
	if query.PageSize > 100 {
		return &ValidationError{Field: "pageSize", Rule: "maximum-100"}
	}
	if query.SortOrder == "" {
		query.SortOrder = "asc"
	}
	if query.SortOrder != "asc" && query.SortOrder != "desc" {
		return &ValidationError{Field: "sortOrder", Rule: "asc-or-desc"}
	}
	if query.SortBy != "" {
		switch query.SortBy {
		case "resource":
		default:
			return &ValidationError{Field: "sortBy", Rule: "unsupported"}
		}
	}
	query.Owner = strings.TrimSpace(query.Owner)
	query.State = strings.TrimSpace(query.State)
	if query.State != "" {
		if err := validateState(query.State, false); err != nil {
			return err
		}
	}
	return nil
}

var resourcePattern = regexp.MustCompile("^[A-Za-z0-9._-]+$")

func validateResource(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "resource", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 2 {
		return &ValidationError{Field: "resource", Rule: "minimum-length-2"}
	}
	if utf8.RuneCountInString(value) > 120 {
		return &ValidationError{Field: "resource", Rule: "maximum-length-120"}
	}
	if !resourcePattern.MatchString(value) {
		return &ValidationError{Field: "resource", Rule: "pattern"}
	}
	return nil
}

func validateOwner(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "owner", Rule: "required"}
		}
		return nil
	}
	return nil
}

func validateState(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "state", Rule: "required"}
		}
		return nil
	}
	switch value {
	case "contracted":
	case "implemented":
	case "inventoried":
	case "verified":
	default:
		return &ValidationError{Field: "state", Rule: "enum"}
	}
	return nil
}

func validateEvidence(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "evidence", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) > 500 {
		return &ValidationError{Field: "evidence", Rule: "maximum-length-500"}
	}
	return nil
}
