// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"context"
	"time"
)

// DomainEvent is the narrow typed event boundary for this module checkpoint.
// It is intentionally not coupled to the v1.1 EventBus work.
type DomainEvent interface {
	EventName() string
}

// EventCollector receives typed events after the database transaction commits.
type EventCollector interface {
	Collect(context.Context, DomainEvent)
}

type discardEventCollector struct{}

func (discardEventCollector) Collect(context.Context, DomainEvent) {}

// LegacyMigrationCheckpointCreatedEvent is emitted for platform.legacycheckpoint.created.
type LegacyMigrationCheckpointCreatedEvent struct {
	ResourceID string    `json:"resourceID"`
	OccurredAt time.Time `json:"occurredAt"`
}

func (LegacyMigrationCheckpointCreatedEvent) EventName() string {
	return "platform.legacycheckpoint.created"
}

// LegacyMigrationCheckpointUpdatedEvent is emitted for platform.legacycheckpoint.updated.
type LegacyMigrationCheckpointUpdatedEvent struct {
	ResourceID    string    `json:"resourceID"`
	ChangedFields []string  `json:"changedFields"`
	OccurredAt    time.Time `json:"occurredAt"`
}

func (LegacyMigrationCheckpointUpdatedEvent) EventName() string {
	return "platform.legacycheckpoint.updated"
}
