// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const LegacyMigrationCheckpointMigrationID migration.MigrationID = "20260901110000"

var createLegacyMigrationCheckpointTableDDL = map[string]string{
	"sqlite":   "CREATE TABLE IF NOT EXISTS \"biz_legacy_migration_checkpoints\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" DATETIME NOT NULL,\n  \"updated_at\" DATETIME NOT NULL,\n  \"deleted_at\" DATETIME NULL,\n  \"resource\" VARCHAR(120) NOT NULL,\n  \"owner\" VARCHAR(255) NOT NULL,\n  \"state\" VARCHAR(255) NOT NULL DEFAULT 'inventoried',\n  \"evidence\" VARCHAR(500),\n  \"release_blocking\" BOOLEAN NOT NULL DEFAULT 1,\n  CONSTRAINT \"ck_biz_legacy_migration_checkpoints_state\" CHECK (\"state\" IN ('contracted', 'implemented', 'inventoried', 'verified'))\n)",
	"postgres": "CREATE TABLE IF NOT EXISTS \"biz_legacy_migration_checkpoints\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" TIMESTAMPTZ NOT NULL,\n  \"updated_at\" TIMESTAMPTZ NOT NULL,\n  \"deleted_at\" TIMESTAMPTZ NULL,\n  \"resource\" VARCHAR(120) NOT NULL,\n  \"owner\" VARCHAR(255) NOT NULL,\n  \"state\" VARCHAR(255) NOT NULL DEFAULT 'inventoried',\n  \"evidence\" VARCHAR(500),\n  \"release_blocking\" BOOLEAN NOT NULL DEFAULT TRUE,\n  CONSTRAINT \"ck_biz_legacy_migration_checkpoints_state\" CHECK (\"state\" IN ('contracted', 'implemented', 'inventoried', 'verified'))\n)",
	"mysql":    "CREATE TABLE IF NOT EXISTS `biz_legacy_migration_checkpoints` (\n  `id` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,\n  `created_at` DATETIME(3) NOT NULL,\n  `updated_at` DATETIME(3) NOT NULL,\n  `deleted_at` DATETIME(3) NULL,\n  `resource` VARCHAR(120) COLLATE utf8mb4_bin NOT NULL,\n  `owner` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL,\n  `state` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'inventoried',\n  `evidence` VARCHAR(500) COLLATE utf8mb4_bin,\n  `release_blocking` BOOLEAN NOT NULL DEFAULT TRUE,\n  CONSTRAINT `ck_biz_legacy_migration_checkpoints_state` CHECK (`state` IN ('contracted', 'implemented', 'inventoried', 'verified'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin",
}

type legacycheckpointMigrationColumn struct {
	name          string
	databaseTypes map[string]string
	nullable      bool
	primaryKey    bool
	length        int64
	hasDefault    bool
	defaultValue  string
}

var legacycheckpointMigrationColumns = []legacycheckpointMigrationColumn{
	{
		name: "id",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   true,
		length:       64,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "created_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "updated_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "deleted_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     true,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "resource",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       120,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "owner",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       255,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "state",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       255,
		hasDefault:   true,
		defaultValue: "inventoried",
	},
	{
		name: "evidence",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     true,
		primaryKey:   false,
		length:       500,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "release_blocking",
		databaseTypes: map[string]string{
			"sqlite":   "boolean|bool",
			"postgres": "bool|boolean",
			"mysql":    "tinyint|boolean|bool",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   true,
		defaultValue: "true",
	},
}

type legacycheckpointMigrationIndex struct {
	name    string
	columns []string
	unique  bool
	ddl     map[string]string
}

var legacycheckpointMigrationIndexes = []legacycheckpointMigrationIndex{
	{
		name:    "idx_biz_legacy_migration_checkpoints_deleted_at",
		columns: []string{"deleted_at"},
		unique:  false,
		ddl: map[string]string{
			"sqlite":   "CREATE INDEX IF NOT EXISTS \"idx_biz_legacy_migration_checkpoints_deleted_at\" ON \"biz_legacy_migration_checkpoints\" (\"deleted_at\")",
			"postgres": "CREATE INDEX IF NOT EXISTS \"idx_biz_legacy_migration_checkpoints_deleted_at\" ON \"biz_legacy_migration_checkpoints\" (\"deleted_at\")",
			"mysql":    "CREATE INDEX `idx_biz_legacy_migration_checkpoints_deleted_at` ON `biz_legacy_migration_checkpoints` (`deleted_at`)",
		},
	},
	{
		name:    "ux_biz_legacy_migration_checkpoints_resource",
		columns: []string{"resource"},
		unique:  true,
		ddl: map[string]string{
			"sqlite":   "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_legacy_migration_checkpoints_resource\" ON \"biz_legacy_migration_checkpoints\" (\"resource\")",
			"postgres": "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_legacy_migration_checkpoints_resource\" ON \"biz_legacy_migration_checkpoints\" (\"resource\")",
			"mysql":    "CREATE UNIQUE INDEX `ux_biz_legacy_migration_checkpoints_resource` ON `biz_legacy_migration_checkpoints` (`resource`)",
		},
	},
}

// RegisterMigration registers the complete lossless ID on an explicit runner.
func RegisterMigration(runner *migration.Migration) error {
	if runner == nil {
		return errors.New("legacycheckpoint migration runner is required")
	}
	if err := runner.Register(LegacyMigrationCheckpointMigrationID, migrateLegacyMigrationCheckpoint); err != nil {
		return err
	}
	return runner.Register(LegacyMigrationCheckpointAuthorizationMigrationID, migrateLegacyMigrationCheckpointAuthorization)
}

func migrateLegacyMigrationCheckpoint(db *gorm.DB, version string) error {
	return applyLegacyMigrationCheckpointMigration(db, version, nil)
}

// applyLegacyMigrationCheckpointMigration is an additive, forward-only migration. The
// hook exists solely for deterministic interruption recovery tests.
func applyLegacyMigrationCheckpointMigration(db *gorm.DB, version string, afterTable func() error) error {
	if db == nil {
		return errors.New("legacycheckpoint migration database is required")
	}
	if version != LegacyMigrationCheckpointMigrationID.String() {
		return errors.New("legacycheckpoint migration version mismatch")
	}
	dialect := db.Dialector.Name()
	createDDL, supported := createLegacyMigrationCheckpointTableDDL[dialect]
	if !supported {
		return fmt.Errorf("legacycheckpoint migration: unsupported database dialect %q", dialect)
	}
	if !db.Migrator().HasTable(new(LegacyMigrationCheckpoint)) {
		if err := db.Exec(createDDL).Error; err != nil {
			return errors.New("legacycheckpoint migration: create table failed")
		}
	}
	if afterTable != nil {
		if err := afterTable(); err != nil {
			return fmt.Errorf("legacycheckpoint migration interrupted after table creation: %w", err)
		}
	}
	for _, databaseIndex := range legacycheckpointMigrationIndexes {
		if db.Migrator().HasIndex(new(LegacyMigrationCheckpoint), databaseIndex.name) {
			continue
		}
		if err := db.Exec(databaseIndex.ddl[dialect]).Error; err != nil {
			return errors.New("legacycheckpoint migration: create index failed")
		}
	}
	if err := verifyLegacyMigrationCheckpointSchema(db); err != nil {
		return err
	}
	versionRow := &migrationmodels.Migration{}
	versionRow.SetVersion(version)
	if err := db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "version"}},
		DoNothing: true,
	}).Create(versionRow).Error; err != nil {
		return errors.New("legacycheckpoint migration: record version failed")
	}
	return nil
}

func verifyLegacyMigrationCheckpointSchema(db *gorm.DB) error {
	if !db.Migrator().HasTable(new(LegacyMigrationCheckpoint)) {
		return errors.New("legacycheckpoint migration: table readiness failed")
	}
	columnTypes, err := db.Migrator().ColumnTypes(new(LegacyMigrationCheckpoint))
	if err != nil {
		return errors.New("legacycheckpoint migration: column shape readiness failed")
	}
	columnsByName := make(map[string]gorm.ColumnType, len(columnTypes))
	for _, columnType := range columnTypes {
		columnsByName[columnType.Name()] = columnType
	}
	dialect := db.Dialector.Name()
	for _, expected := range legacycheckpointMigrationColumns {
		actual, ok := columnsByName[expected.name]
		if !ok || !migrationDatabaseTypeAllowed(expected.databaseTypes[dialect], actual.DatabaseTypeName()) {
			return errors.New("legacycheckpoint migration: column shape readiness failed")
		}
		nullable, nullableKnown := actual.Nullable()
		if !nullableKnown || nullable != expected.nullable {
			return errors.New("legacycheckpoint migration: column shape readiness failed")
		}
		primaryKey, primaryKeyKnown := actual.PrimaryKey()
		if !primaryKeyKnown || primaryKey != expected.primaryKey {
			return errors.New("legacycheckpoint migration: column shape readiness failed")
		}
		if expected.length > 0 {
			length, lengthKnown := actual.Length()
			if !lengthKnown || length != expected.length {
				return errors.New("legacycheckpoint migration: column shape readiness failed")
			}
		}
		defaultValue, hasDefault := actual.DefaultValue()
		if hasDefault != expected.hasDefault || (hasDefault && normalizeMigrationDefault(defaultValue) != normalizeMigrationDefault(expected.defaultValue)) {
			return errors.New("legacycheckpoint migration: column shape readiness failed")
		}
	}
	for _, expected := range legacycheckpointMigrationIndexes {
		columns, unique, err := loadLegacyMigrationCheckpointMigrationIndexShape(db, dialect, expected.name)
		if err != nil || !migrationStringSlicesEqual(columns, expected.columns) || unique != expected.unique {
			return errors.New("legacycheckpoint migration: index readiness failed")
		}
	}
	return verifyLegacyMigrationCheckpointChecks(db)
}

func loadLegacyMigrationCheckpointMigrationIndexShape(db *gorm.DB, dialect, name string) ([]string, bool, error) {
	rows := make([]struct {
		ColumnName string `gorm:"column:column_name"`
		IsUnique   bool   `gorm:"column:is_unique"`
	}, 0)
	var query string
	switch dialect {
	case "sqlite":
		query = "SELECT info.name AS column_name, list.\"unique\" <> 0 AS is_unique FROM pragma_index_list(?) AS list, pragma_index_info(list.name) AS info WHERE list.name = ? ORDER BY info.seqno"
	case "mysql":
		query = "SELECT column_name, non_unique = 0 AS is_unique FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = ? AND index_name = ? ORDER BY seq_in_index"
	case "postgres":
		query = "SELECT attribute.attname AS column_name, catalog.indisunique AS is_unique FROM pg_index AS catalog JOIN pg_class AS table_class ON table_class.oid = catalog.indrelid JOIN pg_namespace AS namespace ON namespace.oid = table_class.relnamespace JOIN pg_class AS index_class ON index_class.oid = catalog.indexrelid JOIN LATERAL unnest(catalog.indkey) WITH ORDINALITY AS key(attnum, position) ON true JOIN pg_attribute AS attribute ON attribute.attrelid = table_class.oid AND attribute.attnum = key.attnum WHERE namespace.nspname = current_schema() AND table_class.relname = ? AND index_class.relname = ? ORDER BY key.position"
	default:
		return nil, false, errors.New("legacycheckpoint migration: unsupported index dialect")
	}
	if err := db.Raw(query, "biz_legacy_migration_checkpoints", name).Scan(&rows).Error; err != nil {
		return nil, false, err
	}
	if len(rows) == 0 {
		return nil, false, errors.New("legacycheckpoint migration: index not found")
	}
	columns := make([]string, 0, len(rows))
	unique := rows[0].IsUnique
	for _, row := range rows {
		if row.IsUnique != unique {
			return nil, false, errors.New("legacycheckpoint migration: inconsistent index metadata")
		}
		columns = append(columns, row.ColumnName)
	}
	return columns, unique, nil
}

func migrationStringSlicesEqual(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func migrationDatabaseTypeAllowed(allowed, actual string) bool {
	actual = strings.ToLower(strings.TrimSpace(actual))
	for _, candidate := range strings.Split(allowed, "|") {
		candidate = strings.ToLower(strings.TrimSpace(candidate))
		if actual == candidate || strings.HasPrefix(actual, candidate+"(") {
			return true
		}
	}
	return false
}

func normalizeMigrationDefault(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	for strings.HasPrefix(value, "(") && strings.HasSuffix(value, ")") {
		value = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(value, "("), ")"))
	}
	if cast := strings.Index(value, "::"); cast >= 0 {
		value = value[:cast]
	}
	value = strings.Trim(strings.TrimSpace(value), "'\"")
	switch value {
	case "1", "b'1", "true":
		return "true"
	case "0", "b'0", "false":
		return "false"
	default:
		return value
	}
}

func verifyLegacyMigrationCheckpointChecks(db *gorm.DB) error {
	dialect := db.Dialector.Name()
	var definition string
	switch dialect {
	case "sqlite":
		if err := db.Raw("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", "biz_legacy_migration_checkpoints").Scan(&definition).Error; err != nil {
			return errors.New("legacycheckpoint migration: check readiness failed")
		}
		if !strings.Contains(definition, "ck_biz_legacy_migration_checkpoints_state") || !strings.Contains(normalizeMigrationCheckDefinition(definition), normalizeMigrationCheckDefinition("CHECK (\"state\" IN ('contracted', 'implemented', 'inventoried', 'verified'))")) {
			return errors.New("legacycheckpoint migration: check readiness failed")
		}
	case "postgres":
		if err := db.Raw("SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = ? AND conrelid = ?::regclass", "ck_biz_legacy_migration_checkpoints_state", "biz_legacy_migration_checkpoints").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("legacycheckpoint migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("CHECK (((\"state\")::text = ANY ((ARRAY['contracted'::character varying, 'implemented'::character varying, 'inventoried'::character varying, 'verified'::character varying])::text[])))") {
			return errors.New("legacycheckpoint migration: check shape readiness failed")
		}
	case "mysql":
		if err := db.Raw("SELECT cc.check_clause FROM information_schema.check_constraints AS cc JOIN information_schema.table_constraints AS tc ON tc.constraint_schema = cc.constraint_schema AND tc.constraint_name = cc.constraint_name WHERE tc.constraint_schema = DATABASE() AND tc.table_name = ? AND tc.constraint_name = ? AND tc.constraint_type = 'CHECK'", "biz_legacy_migration_checkpoints", "ck_biz_legacy_migration_checkpoints_state").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("legacycheckpoint migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("(`state` IN ('contracted', 'implemented', 'inventoried', 'verified'))") {
			return errors.New("legacycheckpoint migration: check shape readiness failed")
		}
	default:
		return errors.New("legacycheckpoint migration: unsupported check dialect")
	}
	return nil
}

func normalizeMigrationSQL(value string) string {
	return strings.Join(strings.Fields(strings.ToLower(value)), " ")
}

var migrationCharsetIntroducer = regexp.MustCompile(`_[a-z0-9]+(')`)

func normalizeMigrationCheckDefinition(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "\\'", "'")
	value = migrationCharsetIntroducer.ReplaceAllString(value, "$1")
	return strings.NewReplacer(
		" ", "",
		"\t", "",
		"\r", "",
		"\n", "",
		"`", "",
		"\"", "",
	).Replace(value)
}
