// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func TestLegacyMigrationCheckpointForwardMigrationFreshRepeatAndConstraints(t *testing.T) {
	db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
	runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("fresh migration error = %v", err)
	}
	assertLegacyMigrationCheckpointSchemaReady(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("repeat migration error = %v", err)
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count migration versions: %v", err)
	}
	if versions != 1 {
		t.Fatalf("migration version rows = %d, want 1", versions)
	}
	invalidState := &LegacyMigrationCheckpoint{
		Resource:        "VALUE_01",
		Owner:           "VALUE_01",
		State:           "outside-contract",
		Evidence:        "VALUE_01",
		ReleaseBlocking: true,
	}
	if err := db.Create(invalidState).Error; err == nil {
		t.Fatal("database enum constraint accepted an undeclared value")
	}
}

func TestLegacyMigrationCheckpointForwardMigrationPreservesUpgradeData(t *testing.T) {
	db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
	if err := db.Exec("CREATE TABLE legacy_records (id TEXT PRIMARY KEY, value TEXT NOT NULL)").Error; err != nil {
		t.Fatalf("create legacy table: %v", err)
	}
	if err := db.Exec("INSERT INTO legacy_records (id, value) VALUES (?, ?)", "legacy-1", "preserve-me").Error; err != nil {
		t.Fatalf("insert legacy row: %v", err)
	}
	runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("upgrade migration error = %v", err)
	}
	var value string
	if err := db.Raw("SELECT value FROM legacy_records WHERE id = ?", "legacy-1").Scan(&value).Error; err != nil {
		t.Fatalf("read legacy row: %v", err)
	}
	if value != "preserve-me" {
		t.Fatalf("legacy value = %q", value)
	}
	assertLegacyMigrationCheckpointSchemaReady(t, db)
}

func TestLegacyMigrationCheckpointForwardMigrationRecoversAfterInterruptionWithoutPartialTruth(t *testing.T) {
	db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
	injected := errors.New("injected interruption")
	err := applyLegacyMigrationCheckpointMigration(db, LegacyMigrationCheckpointMigrationID.String(), func() error { return injected })
	if !errors.Is(err, injected) {
		t.Fatalf("interrupted migration error = %v", err)
	}
	if !db.Migrator().HasTable(new(LegacyMigrationCheckpoint)) {
		t.Fatal("interrupted migration did not reach the table checkpoint")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count interrupted version rows: %v", err)
	}
	if versions != 0 {
		t.Fatalf("interrupted migration recorded completion: %d", versions)
	}
	runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("recovery migration error = %v", err)
	}
	assertLegacyMigrationCheckpointSchemaReady(t, db)
}

func TestLegacyMigrationCheckpointForwardMigrationRejectsExistingColumnShapeDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
	driftedDDL, ok := driftLegacyMigrationCheckpointSQLiteColumnType(createLegacyMigrationCheckpointTableDDL["sqlite"])
	if !ok {
		t.Fatal("test contract could not select a business column to corrupt")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create drifted table: %v", err)
	}
	runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing column shape")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func TestLegacyMigrationCheckpointForwardMigrationRejectsNullableRequiredColumnsWithoutVersionTruth(t *testing.T) {
	t.Run("resource", func(t *testing.T) {
		db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
		driftedDDL, ok := driftLegacyMigrationCheckpointSQLiteRequiredColumnNullable(createLegacyMigrationCheckpointTableDDL["sqlite"], "resource")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertLegacyMigrationCheckpointMigrationVersionAbsent(t, db)
	})
	t.Run("owner", func(t *testing.T) {
		db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
		driftedDDL, ok := driftLegacyMigrationCheckpointSQLiteRequiredColumnNullable(createLegacyMigrationCheckpointTableDDL["sqlite"], "owner")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertLegacyMigrationCheckpointMigrationVersionAbsent(t, db)
	})
	t.Run("state", func(t *testing.T) {
		db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
		driftedDDL, ok := driftLegacyMigrationCheckpointSQLiteRequiredColumnNullable(createLegacyMigrationCheckpointTableDDL["sqlite"], "state")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertLegacyMigrationCheckpointMigrationVersionAbsent(t, db)
	})
	t.Run("release_blocking", func(t *testing.T) {
		db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
		driftedDDL, ok := driftLegacyMigrationCheckpointSQLiteRequiredColumnNullable(createLegacyMigrationCheckpointTableDDL["sqlite"], "release_blocking")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertLegacyMigrationCheckpointMigrationVersionAbsent(t, db)
	})
}

func TestLegacyMigrationCheckpointForwardMigrationRejectsIndexShapeDriftWithoutVersionTruth(t *testing.T) {
	for _, test := range []struct {
		name       string
		wrongIndex func(legacycheckpointMigrationIndex) string
	}{
		{
			name: "columns",
			wrongIndex: func(index legacycheckpointMigrationIndex) string {
				keyword := ""
				if index.unique {
					keyword = "UNIQUE "
				}
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_legacy_migration_checkpoints\" (\"id\")"
			},
		},
		{
			name: "uniqueness",
			wrongIndex: func(index legacycheckpointMigrationIndex) string {
				keyword := "UNIQUE "
				if index.unique {
					keyword = ""
				}
				columns := "\"" + strings.Join(index.columns, "\", \"") + "\""
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_legacy_migration_checkpoints\" (" + columns + ")"
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
			if err := db.Exec(createLegacyMigrationCheckpointTableDDL["sqlite"]).Error; err != nil {
				t.Fatalf("create table: %v", err)
			}
			if len(legacycheckpointMigrationIndexes) == 0 {
				t.Fatal("test contract requires an index")
			}
			if err := db.Exec(test.wrongIndex(legacycheckpointMigrationIndexes[0])).Error; err != nil {
				t.Fatalf("create wrong-shape index: %v", err)
			}
			runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
			if err := runner.MigrateContext(context.Background()); err == nil {
				t.Fatal("migration accepted an incompatible same-name index")
			}
			assertLegacyMigrationCheckpointMigrationVersionAbsent(t, db)
		})
	}
}

func TestLegacyMigrationCheckpointGeneratedMigrationDuplicateRegistrationFailsPreflightWithoutDatabase(t *testing.T) {
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("first RegisterMigration() error = %v", err)
	}
	if err := RegisterMigration(runner); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("duplicate RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("ValidateRegistrations() error = %v, want duplicate ID", err)
	}
	if runner.GetDb() != nil {
		t.Fatal("registration preflight unexpectedly required a database")
	}
}

func TestLegacyMigrationCheckpointForwardMigrationRejectsExistingCheckBodyDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedLegacyMigrationCheckpointDatabase(t)
	originalValue := "'" + "contracted" + "'"
	driftedDDL := strings.Replace(createLegacyMigrationCheckpointTableDDL["sqlite"], originalValue, "'contract-drift'", 1)
	if driftedDDL == createLegacyMigrationCheckpointTableDDL["sqlite"] {
		t.Fatal("test contract could not corrupt the check body")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create check-drifted table: %v", err)
	}
	runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing check body")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("check-drifted migration version count = %d, err=%v", versions, err)
	}
}

func driftLegacyMigrationCheckpointSQLiteColumnType(ddl string) (string, bool) {
	for _, column := range legacycheckpointMigrationColumns[4:] {
		var declaredType string
		if column.length > 0 {
			declaredType = fmt.Sprintf("VARCHAR(%d)", column.length)
		} else {
			declaredType = "BOOLEAN"
		}
		original := fmt.Sprintf("%q %s", column.name, declaredType)
		replacement := fmt.Sprintf("%q BLOB", column.name)
		if drifted := strings.Replace(ddl, original, replacement, 1); drifted != ddl {
			return drifted, true
		}
	}
	return ddl, false
}

func driftLegacyMigrationCheckpointSQLiteRequiredColumnNullable(ddl, column string) (string, bool) {
	token := fmt.Sprintf("%q", column)
	for _, line := range strings.SplitAfter(ddl, "\n") {
		if !strings.Contains(line, token) || !strings.Contains(line, " NOT NULL") {
			continue
		}
		driftedLine := strings.Replace(line, " NOT NULL", "", 1)
		return strings.Replace(ddl, line, driftedLine, 1), true
	}
	return ddl, false
}

func assertLegacyMigrationCheckpointMigrationVersionAbsent(t *testing.T, db *gorm.DB) {
	t.Helper()
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func openUnmigratedLegacyMigrationCheckpointDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "migration.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareLegacyMigrationCheckpointAuthorizationTestSchema(t, db)
	return db
}

func configuredLegacyMigrationCheckpointMigrationRunner(t *testing.T, db *gorm.DB) *migration.Migration {
	t.Helper()
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); err != nil {
		t.Fatalf("ValidateRegistrations() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	return runner
}

func assertLegacyMigrationCheckpointSchemaReady(t *testing.T, db *gorm.DB) {
	t.Helper()
	if err := verifyLegacyMigrationCheckpointSchema(db); err != nil {
		t.Fatalf("schema readiness error = %v", err)
	}
	if !db.Migrator().HasIndex(new(LegacyMigrationCheckpoint), "idx_biz_legacy_migration_checkpoints_deleted_at") {
		t.Fatal("missing index idx_biz_legacy_migration_checkpoints_deleted_at")
	}
	if !db.Migrator().HasIndex(new(LegacyMigrationCheckpoint), "ux_biz_legacy_migration_checkpoints_resource") {
		t.Fatal("missing index ux_biz_legacy_migration_checkpoints_resource")
	}
}
