// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
	"time"

	configgormdb "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/config/gormdb"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

const (
	legacycheckpointMySQLDSNEnv          = "MSS_LEGACYCHECKPOINT_TEST_MYSQL_DSN"
	legacycheckpointPostgresDSNEnv       = "MSS_LEGACYCHECKPOINT_TEST_POSTGRES_DSN"
	legacycheckpointProviderTestDatabase = "mss_legacycheckpoint_test"
)

func TestLegacyMigrationCheckpointMigrationMySQLIntegration(t *testing.T) {
	runLegacyMigrationCheckpointMigrationProviderIntegration(t, "mysql", legacycheckpointMySQLDSNEnv)
}

func TestLegacyMigrationCheckpointMigrationPostgresIntegration(t *testing.T) {
	runLegacyMigrationCheckpointMigrationProviderIntegration(t, "postgres", legacycheckpointPostgresDSNEnv)
}

func TestLegacyMigrationCheckpointMigrationMySQLRejectsCheckAndIndexDrift(t *testing.T) {
	runLegacyMigrationCheckpointMigrationProviderDrift(t, "mysql", legacycheckpointMySQLDSNEnv)
}

func TestLegacyMigrationCheckpointMigrationPostgresRejectsCheckAndIndexDrift(t *testing.T) {
	runLegacyMigrationCheckpointMigrationProviderDrift(t, "postgres", legacycheckpointPostgresDSNEnv)
}

func runLegacyMigrationCheckpointMigrationProviderIntegration(t *testing.T, dialect, environment string) {
	t.Helper()
	dsn := strings.TrimSpace(os.Getenv(environment))
	if dsn == "" {
		t.Skip(environment + " is not set")
	}
	db := openLegacyMigrationCheckpointProviderDatabase(t, dialect, dsn)

	t.Run("fresh repeat constraints", func(t *testing.T) {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		createLegacyMigrationCheckpointProviderMigrationTable(t, db, dialect)
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		for attempt := 1; attempt <= 2; attempt++ {
			if err := runner.MigrateContext(context.Background()); err != nil {
				t.Fatalf("%s migration attempt %d: %v", dialect, attempt, err)
			}
		}
		assertLegacyMigrationCheckpointSchemaReady(t, db)
		valid := &LegacyMigrationCheckpoint{
			Resource:        "VALUE_01",
			Owner:           "VALUE_01",
			State:           "contracted",
			Evidence:        "VALUE_01",
			ReleaseBlocking: true,
		}
		if err := db.Create(valid).Error; err != nil {
			t.Fatalf("%s create valid row: %v", dialect, err)
		}
		duplicate := &LegacyMigrationCheckpoint{
			Resource:        "VALUE_01",
			Owner:           "VALUE_01",
			State:           "contracted",
			Evidence:        "VALUE_01",
			ReleaseBlocking: true,
		}
		if err := db.Create(duplicate).Error; err == nil {
			t.Fatalf("%s unique constraint accepted a duplicate", dialect)
		}
		invalidState := &LegacyMigrationCheckpoint{
			Resource:        "VALUE_02",
			Owner:           "VALUE_02",
			State:           "outside-contract",
			Evidence:        "VALUE_02",
			ReleaseBlocking: false,
		}
		if err := db.Create(invalidState).Error; err == nil {
			t.Fatalf("%s enum constraint accepted an undeclared value", dialect)
		}
		var versions int64
		if err := db.Table("mss_boot_migration").Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 1 {
			t.Fatalf("%s migration version count = %d, err=%v", dialect, versions, err)
		}
	})

	t.Run("interrupted recovery", func(t *testing.T) {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		createLegacyMigrationCheckpointProviderMigrationTable(t, db, dialect)
		injected := errors.New("provider interruption")
		if err := applyLegacyMigrationCheckpointMigration(db, LegacyMigrationCheckpointMigrationID.String(), func() error { return injected }); !errors.Is(err, injected) {
			t.Fatalf("%s interrupted migration error = %v", dialect, err)
		}
		var versions int64
		if err := db.Table("mss_boot_migration").Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
			t.Fatalf("%s interrupted version count = %d, err=%v", dialect, versions, err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err != nil {
			t.Fatalf("%s recovery migration: %v", dialect, err)
		}
		assertLegacyMigrationCheckpointSchemaReady(t, db)
	})

	t.Run("runtime conflicts and escaped search without TranslateError", func(t *testing.T) {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		createLegacyMigrationCheckpointProviderMigrationTable(t, db, dialect)
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err != nil {
			t.Fatalf("%s runtime migration: %v", dialect, err)
		}
		collector := &collectingLegacyMigrationCheckpointEvents{db: db}
		service, err := NewService(db, collector)
		if err != nil {
			t.Fatalf("%s NewService(): %v", dialect, err)
		}
		first, err := service.Create(context.Background(), validLegacyMigrationCheckpointInput())
		if err != nil {
			t.Fatalf("%s Create(first): %v", dialect, err)
		}
		if _, err := service.Create(context.Background(), validLegacyMigrationCheckpointInput()); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
			t.Fatalf("%s Create(duplicate without TranslateError) error = %v", dialect, err)
		}
		secondInput := validLegacyMigrationCheckpointInput()
		secondInput.Resource = "VALUE_02"
		secondInput.Owner = "VALUE_02"
		secondInput.Evidence = "VALUE_02"
		second, err := service.Create(context.Background(), secondInput)
		if err != nil {
			t.Fatalf("%s Create(second): %v", dialect, err)
		}
		page, err := service.List(context.Background(), ListLegacyMigrationCheckpointQuery{Q: "%", Current: 1, PageSize: 10})
		if err != nil {
			t.Fatalf("%s escaped wildcard List(): %v", dialect, err)
		}
		if page.Total != 0 {
			t.Fatalf("%s escaped wildcard search matched %d rows", dialect, page.Total)
		}
		if err := db.Exec("CREATE UNIQUE INDEX ux_legacycheckpoint_provider_update_conflict ON biz_legacy_migration_checkpoints (owner)").Error; err != nil {
			t.Fatalf("%s create update conflict index: %v", dialect, err)
		}
		conflictingValue := second.Owner
		if _, err := service.Update(context.Background(), first.ID, &UpdateLegacyMigrationCheckpointInput{Owner: &conflictingValue}); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
			t.Fatalf("%s Update(duplicate without TranslateError) error = %v", dialect, err)
		}
		declaredConflict := second.Resource
		if _, err := service.Update(context.Background(), first.ID, &UpdateLegacyMigrationCheckpointInput{Resource: &declaredConflict}); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
			t.Fatalf("%s Update(declared duplicate without TranslateError) error = %v", dialect, err)
		}
	})
}

func runLegacyMigrationCheckpointMigrationProviderDrift(t *testing.T, dialect, environment string) {
	t.Helper()
	dsn := strings.TrimSpace(os.Getenv(environment))
	if dsn == "" {
		t.Skip(environment + " is not set")
	}
	db := openLegacyMigrationCheckpointProviderDatabase(t, dialect, dsn)

	t.Run("same-name index shape", func(t *testing.T) {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		createLegacyMigrationCheckpointProviderMigrationTable(t, db, dialect)
		if err := db.Exec(createLegacyMigrationCheckpointTableDDL[dialect]).Error; err != nil {
			t.Fatalf("%s create table: %v", dialect, err)
		}
		if len(legacycheckpointMigrationIndexes) == 0 {
			t.Fatal("test contract requires an index")
		}
		index := legacycheckpointMigrationIndexes[0]
		wrongColumn := "id"
		if len(index.columns) == 1 && index.columns[0] == wrongColumn {
			wrongColumn = "created_at"
		}
		keyword := ""
		if index.unique {
			keyword = "UNIQUE "
		}
		ddl := "CREATE " + keyword + "INDEX " + quoteLegacyMigrationCheckpointProviderIdentifier(dialect, index.name) + " ON " + quoteLegacyMigrationCheckpointProviderIdentifier(dialect, "biz_legacy_migration_checkpoints") + " (" + quoteLegacyMigrationCheckpointProviderIdentifier(dialect, wrongColumn) + ")"
		if err := db.Exec(ddl).Error; err != nil {
			t.Fatalf("%s create wrong-shape index: %v", dialect, err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatalf("%s migration accepted a same-name wrong-column index", dialect)
		}
		assertLegacyMigrationCheckpointProviderVersionAbsent(t, db, dialect)
	})

	t.Run("permissive check body", func(t *testing.T) {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		createLegacyMigrationCheckpointProviderMigrationTable(t, db, dialect)
		driftedDDL, ok := driftLegacyMigrationCheckpointProviderCheck(createLegacyMigrationCheckpointTableDDL[dialect], dialect, "ck_biz_legacy_migration_checkpoints_state")
		if !ok {
			t.Fatal("test contract could not make the check permissive")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("%s create check-drifted table: %v", dialect, err)
		}
		runner := configuredLegacyMigrationCheckpointMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatalf("%s migration accepted a permissive check body", dialect)
		}
		assertLegacyMigrationCheckpointProviderVersionAbsent(t, db, dialect)
	})
}

func quoteLegacyMigrationCheckpointProviderIdentifier(dialect, value string) string {
	if dialect == "mysql" {
		return "`" + value + "`"
	}
	return "\"" + value + "\""
}

func driftLegacyMigrationCheckpointProviderCheck(ddl, dialect, name string) (string, bool) {
	marker := "CONSTRAINT " + quoteLegacyMigrationCheckpointProviderIdentifier(dialect, name) + " CHECK ("
	start := strings.Index(ddl, marker)
	if start < 0 {
		return ddl, false
	}
	end := strings.Index(ddl[start:], "\n")
	if end < 0 {
		end = len(ddl) - start
	}
	line := ddl[start : start+end]
	closing := strings.LastIndex(line, ")")
	if closing < 0 {
		return ddl, false
	}
	driftedLine := line[:closing] + " OR 1 = 1" + line[closing:]
	return strings.Replace(ddl, line, driftedLine, 1), true
}

func assertLegacyMigrationCheckpointProviderVersionAbsent(t *testing.T, db *gorm.DB, dialect string) {
	t.Helper()
	var versions int64
	if err := db.Table("mss_boot_migration").Where("version = ?", LegacyMigrationCheckpointMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("%s drifted migration version count = %d, err=%v", dialect, versions, err)
	}
}

func openLegacyMigrationCheckpointProviderDatabase(t *testing.T, dialect, dsn string) *gorm.DB {
	t.Helper()
	dialector, ok := configgormdb.Opens[dialect]
	if !ok {
		t.Fatalf("provider dialect %q is unavailable", dialect)
	}
	db, err := gorm.Open(dialector(dsn), &gorm.Config{
		DisableForeignKeyConstraintWhenMigrating: true,
		TranslateError:                           false,
		Logger:                                   logger.Discard,
	})
	if err != nil {
		t.Fatalf("open %s provider database: %v", dialect, err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("obtain %s provider handle: %v", dialect, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	if err := sqlDB.PingContext(ctx); err != nil {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("ping %s provider database: %v", dialect, err)
	}
	var databaseName string
	query := "SELECT current_database()"
	if dialect == "mysql" {
		query = "SELECT DATABASE()"
	}
	if err := db.WithContext(ctx).Raw(query).Scan(&databaseName).Error; err != nil {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("read %s provider database name: %v", dialect, err)
	}
	if databaseName != legacycheckpointProviderTestDatabase {
		cancel()
		_ = sqlDB.Close()
		t.Fatalf("refusing destructive %s test outside allowlisted database %q", dialect, legacycheckpointProviderTestDatabase)
	}
	t.Cleanup(func() {
		resetLegacyMigrationCheckpointProviderTables(t, db)
		cancel()
		if err := sqlDB.Close(); err != nil {
			t.Errorf("close %s provider database: %v", dialect, err)
		}
	})
	return db.WithContext(ctx)
}

func resetLegacyMigrationCheckpointProviderTables(t *testing.T, db *gorm.DB) {
	t.Helper()
	for _, table := range []string{
		"biz_legacy_migration_checkpoints",
		"mss_boot_casbin_rule",
		"mss_boot_config_revisions",
		"mss_boot_menus",
		"mss_boot_roles",
		"mss_boot_migration",
	} {
		if err := db.Exec("DROP TABLE IF EXISTS " + table).Error; err != nil {
			t.Fatalf("drop %s: %v", table, err)
		}
	}
}

func createLegacyMigrationCheckpointProviderMigrationTable(t *testing.T, db *gorm.DB, dialect string) {
	t.Helper()
	ddl := "CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time TIMESTAMPTZ NOT NULL)"
	if dialect == "mysql" {
		ddl = "CREATE TABLE mss_boot_migration (version VARCHAR(255) PRIMARY KEY, apply_time DATETIME(3) NOT NULL) ENGINE=InnoDB"
	}
	if err := db.Exec(ddl).Error; err != nil {
		t.Fatalf("create %s migration table: %v", dialect, err)
	}
	prepareLegacyMigrationCheckpointAuthorizationTestSchema(t, db)
}
