// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/response/actions"

// LegacyMigrationCheckpoint is the persistent entity generated for 存量迁移检查点.
type LegacyMigrationCheckpoint struct {
	actions.ModelGorm
	Resource        string `json:"resource" gorm:"column:resource;type:varchar(120);not null;uniqueIndex:ux_biz_legacy_migration_checkpoints_resource;comment:资源"`
	Owner           string `json:"owner" gorm:"column:owner;type:varchar(255);not null;comment:归属平台"`
	State           string `json:"state" gorm:"column:state;type:varchar(255);not null;default:inventoried;comment:实施状态"`
	Evidence        string `json:"evidence" gorm:"column:evidence;type:varchar(500);comment:验收证据"`
	ReleaseBlocking bool   `json:"releaseBlocking" gorm:"column:release_blocking;type:boolean;not null;default:true;comment:阻断发布"`
}

// TableName returns the stable database table name.
func (*LegacyMigrationCheckpoint) TableName() string {
	return "biz_legacy_migration_checkpoints"
}
