// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"errors"
	"testing"

	"github.com/mss-boot-io/mss-boot-admin/admin/business"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	"gorm.io/gorm"
)

func TestLegacyMigrationCheckpointTableName(t *testing.T) {
	if got, want := new(LegacyMigrationCheckpoint).TableName(), "biz_legacy_migration_checkpoints"; got != want {
		t.Fatalf("TableName() = %q, want %q", got, want)
	}
}

func TestLegacyMigrationCheckpointMigrationIdentityIsComplete(t *testing.T) {
	if got, want := LegacyMigrationCheckpointMigrationID.String(), "20260901110000"; got != want {
		t.Fatalf("migration ID = %q, want %q", got, want)
	}
}

func TestLegacyMigrationCheckpointAuthorizationMigrationIdentityIsComplete(t *testing.T) {
	if got, want := LegacyMigrationCheckpointAuthorizationMigrationID.String(), "20260901110001"; got != want {
		t.Fatalf("authorization migration ID = %q, want %q", got, want)
	}
}

func TestLegacyMigrationCheckpointPermissionCodesAreUnique(t *testing.T) {
	codes := []string{
		"legacycheckpoint:create",
		"legacycheckpoint:delete",
		"legacycheckpoint:export",
		"legacycheckpoint:list",
		"legacycheckpoint:read",
		"legacycheckpoint:update",
	}
	seen := make(map[string]struct{}, len(codes))
	for _, code := range codes {
		if _, exists := seen[code]; exists {
			t.Fatalf("duplicate permission code %q", code)
		}
		seen[code] = struct{}{}
	}
}

func TestLegacyMigrationCheckpointOperationContractMatchesSpecification(t *testing.T) {
	contracts := OperationContracts()
	if got, want := len(contracts), 6; got != want {
		t.Fatalf("operation contracts = %d, want %d", got, want)
	}
	want := map[string]string{
		"POST /admin/api/legacy-migration-checkpoints":        PermissionCreate,
		"DELETE /admin/api/legacy-migration-checkpoints/{id}": PermissionDelete,
		"GET /admin/api/legacy-migration-checkpoints/export":  PermissionExport,
		"GET /admin/api/legacy-migration-checkpoints/{id}":    PermissionRead,
		"GET /admin/api/legacy-migration-checkpoints":         PermissionList,
		"PUT /admin/api/legacy-migration-checkpoints/{id}":    PermissionUpdate,
	}
	for _, contract := range contracts {
		key := contract.Method + " " + contract.Path
		if permission, exists := want[key]; !exists || permission != contract.Permission {
			t.Fatalf("unexpected operation contract %#v", contract)
		}
		delete(want, key)
	}
	if len(want) != 0 {
		t.Fatalf("missing operation contracts: %#v", want)
	}
}

func TestLegacyMigrationCheckpointDescriptorProjectsAuthorizationMetadataWithoutInferringComposition(t *testing.T) {
	module := Module()
	if got, want := module.Name(), "legacycheckpoint"; got != want {
		t.Fatalf("Module().Name() = %q, want %q", got, want)
	}
	registry, err := business.Compose(migration.New(), module)
	if err != nil {
		t.Fatalf("compose generated module: %v", err)
	}
	descriptors := registry.Descriptors()
	if len(descriptors) != 1 {
		t.Fatalf("generated descriptors = %#v", descriptors)
	}
	descriptor := descriptors[0]
	if descriptor.Migrate != nil {
		t.Fatal("generated descriptor must not expose AutoMigrate or another inferred migration hook")
	}
	if got, want := len(descriptor.Permissions), 6; got != want {
		t.Fatalf("descriptor permissions = %d, want %d", got, want)
	}
	if got, want := descriptor.Menu.Path, "/legacy-migration-checkpoints"; got != want {
		t.Fatalf("descriptor menu path = %q, want %q", got, want)
	}
	runner, err := registry.MigrationRunner()
	if err != nil {
		t.Fatalf("clone generated migration runner: %v", err)
	}
	if err := runner.Register(LegacyMigrationCheckpointMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated schema migration was not registered: %v", err)
	}
	if err := runner.Register(LegacyMigrationCheckpointAuthorizationMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated authorization migration was not registered: %v", err)
	}
}
