// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"reflect"
	"sort"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const maxLegacyMigrationCheckpointExportRows = 10000

var (
	ErrLegacyMigrationCheckpointNotFound    = errors.New("legacycheckpoint not found")
	ErrLegacyMigrationCheckpointConflict    = errors.New("legacycheckpoint conflict")
	ErrLegacyMigrationCheckpointPersistence = errors.New("legacycheckpoint persistence unavailable")
	ErrLegacyMigrationCheckpointExportLimit = errors.New("legacycheckpoint export limit exceeded")
)

// Application is the generated backend use-case boundary consumed by HTTP.
type Application interface {
	List(context.Context, ListLegacyMigrationCheckpointQuery) (LegacyMigrationCheckpointPage, error)
	Get(context.Context, string) (*LegacyMigrationCheckpoint, error)
	Create(context.Context, *CreateLegacyMigrationCheckpointInput) (*LegacyMigrationCheckpoint, error)
	Update(context.Context, string, *UpdateLegacyMigrationCheckpointInput) (*LegacyMigrationCheckpoint, error)
	Delete(context.Context, string) error
	Export(context.Context, ListLegacyMigrationCheckpointQuery, io.Writer) error
}

// Service owns authoritative legacycheckpoint transactions.
type Service struct {
	db     *gorm.DB
	events EventCollector
}

func NewService(db *gorm.DB, events EventCollector) (*Service, error) {
	if db == nil {
		return nil, errors.New("legacycheckpoint database is required")
	}
	if isNilEventCollector(events) {
		return nil, errors.New("legacycheckpoint event collector is required")
	}
	return &Service{db: db, events: events}, nil
}

func isNilEventCollector(events EventCollector) bool {
	if events == nil {
		return true
	}
	value := reflect.ValueOf(events)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

func (service *Service) List(ctx context.Context, query ListLegacyMigrationCheckpointQuery) (LegacyMigrationCheckpointPage, error) {
	if service == nil || service.db == nil {
		return LegacyMigrationCheckpointPage{}, ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return LegacyMigrationCheckpointPage{}, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := query.normalizeAndValidate(); err != nil {
		return LegacyMigrationCheckpointPage{}, err
	}
	db := applyLegacyMigrationCheckpointQuery(service.db.WithContext(ctx).Model(new(LegacyMigrationCheckpoint)), query)
	var total int64
	if err := db.Count(&total).Error; err != nil {
		return LegacyMigrationCheckpointPage{}, normalizeLegacyMigrationCheckpointDBError(err)
	}
	var records []LegacyMigrationCheckpoint
	db = orderLegacyMigrationCheckpointQuery(db, query)
	if err := db.Offset((query.Current - 1) * query.PageSize).Limit(query.PageSize).Find(&records).Error; err != nil {
		return LegacyMigrationCheckpointPage{}, normalizeLegacyMigrationCheckpointDBError(err)
	}
	return LegacyMigrationCheckpointPage{Data: records, Total: total, Current: query.Current, PageSize: query.PageSize}, nil
}

func (service *Service) Get(ctx context.Context, id string) (*LegacyMigrationCheckpoint, error) {
	if service == nil || service.db == nil {
		return nil, ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	var record LegacyMigrationCheckpoint
	if err := service.db.WithContext(ctx).First(&record, "id = ?", id).Error; err != nil {
		return nil, normalizeLegacyMigrationCheckpointDBError(err)
	}
	return &record, nil
}

func (service *Service) Create(ctx context.Context, input *CreateLegacyMigrationCheckpointInput) (*LegacyMigrationCheckpoint, error) {
	if service == nil || service.db == nil {
		return nil, ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	record := &LegacyMigrationCheckpoint{
		Resource:        input.Resource,
		Owner:           input.Owner,
		State:           input.State,
		Evidence:        input.Evidence,
		ReleaseBlocking: boolValue(input.ReleaseBlocking),
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		return tx.Create(record).Error
	}); err != nil {
		return nil, service.normalizeLegacyMigrationCheckpointWriteError(ctx, "", record, err)
	}
	service.events.Collect(ctx, LegacyMigrationCheckpointCreatedEvent{ResourceID: record.ID, OccurredAt: record.CreatedAt})
	return record, nil
}

func (service *Service) Update(ctx context.Context, id string, input *UpdateLegacyMigrationCheckpointInput) (*LegacyMigrationCheckpoint, error) {
	if service == nil || service.db == nil {
		return nil, ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	changedFields := make([]string, 0, 5)
	updates := make(map[string]any, 5)
	if input.Resource != nil {
		updates["resource"] = *input.Resource
		changedFields = append(changedFields, "resource")
	}
	if input.Owner != nil {
		updates["owner"] = *input.Owner
		changedFields = append(changedFields, "owner")
	}
	if input.State != nil {
		updates["state"] = *input.State
		changedFields = append(changedFields, "state")
	}
	if input.Evidence != nil {
		updates["evidence"] = *input.Evidence
		changedFields = append(changedFields, "evidence")
	}
	if input.ReleaseBlocking != nil {
		updates["release_blocking"] = *input.ReleaseBlocking
		changedFields = append(changedFields, "releaseBlocking")
	}
	sort.Strings(changedFields)
	var record LegacyMigrationCheckpoint
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		if input.Resource != nil {
			record.Resource = *input.Resource
		}
		if input.Owner != nil {
			record.Owner = *input.Owner
		}
		if input.State != nil {
			record.State = *input.State
		}
		if input.Evidence != nil {
			record.Evidence = *input.Evidence
		}
		if input.ReleaseBlocking != nil {
			record.ReleaseBlocking = *input.ReleaseBlocking
		}
		if err := tx.Model(&record).Updates(updates).Error; err != nil {
			return err
		}
		return tx.First(&record, "id = ?", id).Error
	}); err != nil {
		return nil, service.normalizeLegacyMigrationCheckpointWriteError(ctx, id, &record, err)
	}
	service.events.Collect(ctx, LegacyMigrationCheckpointUpdatedEvent{ResourceID: record.ID, ChangedFields: changedFields, OccurredAt: record.UpdatedAt})
	return &record, nil
}

func (service *Service) Delete(ctx context.Context, id string) error {
	if service == nil || service.db == nil {
		return ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return &ValidationError{Field: "id", Rule: "required"}
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var record LegacyMigrationCheckpoint
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&record).Error
	}); err != nil {
		return normalizeLegacyMigrationCheckpointDBError(err)
	}
	return nil
}

func (service *Service) Export(ctx context.Context, query ListLegacyMigrationCheckpointQuery, destination io.Writer) error {
	if service == nil || service.db == nil {
		return ErrLegacyMigrationCheckpointPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	if destination == nil {
		return &ValidationError{Field: "destination", Rule: "required"}
	}
	query.Current = 1
	query.PageSize = 100
	if err := query.normalizeAndValidate(); err != nil {
		return err
	}
	var records []LegacyMigrationCheckpoint
	db := applyLegacyMigrationCheckpointQuery(service.db.WithContext(ctx).Model(new(LegacyMigrationCheckpoint)), query)
	db = orderLegacyMigrationCheckpointQuery(db, query).Limit(maxLegacyMigrationCheckpointExportRows + 1)
	if err := db.Find(&records).Error; err != nil {
		return normalizeLegacyMigrationCheckpointDBError(err)
	}
	if len(records) > maxLegacyMigrationCheckpointExportRows {
		return ErrLegacyMigrationCheckpointExportLimit
	}
	writer := csv.NewWriter(destination)
	if err := writer.Write([]string{"id", "resource", "owner", "state", "evidence", "releaseBlocking"}); err != nil {
		return ErrLegacyMigrationCheckpointPersistence
	}
	for _, record := range records {
		row := []string{csvSafe(record.ID), csvSafe(fmt.Sprint(record.Resource)), csvSafe(fmt.Sprint(record.Owner)), csvSafe(fmt.Sprint(record.State)), csvSafe(fmt.Sprint(record.Evidence)), csvSafe(fmt.Sprint(record.ReleaseBlocking))}
		if err := writer.Write(row); err != nil {
			return ErrLegacyMigrationCheckpointPersistence
		}
	}
	writer.Flush()
	if writer.Error() != nil {
		return ErrLegacyMigrationCheckpointPersistence
	}
	return nil
}

func applyLegacyMigrationCheckpointQuery(db *gorm.DB, query ListLegacyMigrationCheckpointQuery) *gorm.DB {
	if query.Q != "" {
		pattern := "%" + escapeLike(strings.ToLower(query.Q)) + "%"
		db = db.Where(
			strings.Join([]string{
				"LOWER(resource) LIKE ? ESCAPE '!'",
				"LOWER(evidence) LIKE ? ESCAPE '!'",
			}, " OR "),
			pattern,
			pattern,
		)
	}
	if query.Owner != "" {
		db = db.Where("owner = ?", query.Owner)
	}
	if query.State != "" {
		db = db.Where("state = ?", query.State)
	}
	if query.ReleaseBlocking != nil {
		db = db.Where("release_blocking = ?", *query.ReleaseBlocking)
	}
	return db
}

func orderLegacyMigrationCheckpointQuery(db *gorm.DB, query ListLegacyMigrationCheckpointQuery) *gorm.DB {
	columns := map[string]string{
		"resource": "resource",
	}
	if column := columns[query.SortBy]; column != "" {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: column}, Desc: query.SortOrder == "desc"})
	} else {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: "created_at"}, Desc: true})
	}
	return db.Order(clause.OrderByColumn{Column: clause.Column{Name: "id"}})
}

func normalizeLegacyMigrationCheckpointDBError(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, gorm.ErrRecordNotFound):
		return ErrLegacyMigrationCheckpointNotFound
	case errors.Is(err, gorm.ErrDuplicatedKey), isUniqueConstraintError(err):
		return ErrLegacyMigrationCheckpointConflict
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	default:
		return ErrLegacyMigrationCheckpointPersistence
	}
}

func isUniqueConstraintError(err error) bool {
	type sqlStateError interface {
		SQLState() string
	}
	var sqlState sqlStateError
	if errors.As(err, &sqlState) && sqlState.SQLState() == "23505" {
		return true
	}
	type sqliteCodeError interface {
		Code() int
	}
	var sqliteCode sqliteCodeError
	if errors.As(err, &sqliteCode) && (sqliteCode.Code() == 1555 || sqliteCode.Code() == 2067) {
		return true
	}
	for current := err; current != nil; current = errors.Unwrap(current) {
		value := reflect.ValueOf(current)
		if value.Kind() == reflect.Pointer && !value.IsNil() {
			value = value.Elem()
		}
		if value.Kind() != reflect.Struct {
			continue
		}
		number := value.FieldByName("Number")
		if number.IsValid() && number.CanUint() && number.Kind() >= reflect.Uint && number.Kind() <= reflect.Uint64 && number.Uint() == 1062 {
			return true
		}
	}
	return false
}
func (service *Service) normalizeLegacyMigrationCheckpointWriteError(ctx context.Context, excludeID string, record *LegacyMigrationCheckpoint, err error) error {
	normalized := normalizeLegacyMigrationCheckpointDBError(err)
	if !errors.Is(normalized, ErrLegacyMigrationCheckpointPersistence) {
		return normalized
	}
	conflict, probeErr := service.hasLegacyMigrationCheckpointUniqueConflict(ctx, excludeID, record)
	if probeErr != nil {
		return ErrLegacyMigrationCheckpointPersistence
	}
	if conflict {
		return ErrLegacyMigrationCheckpointConflict
	}
	return normalized
}

func (service *Service) hasLegacyMigrationCheckpointUniqueConflict(ctx context.Context, excludeID string, record *LegacyMigrationCheckpoint) (bool, error) {
	if record == nil {
		return false, nil
	}
	query0 := service.db.WithContext(ctx).Unscoped().Model(new(LegacyMigrationCheckpoint))
	query0 = query0.Where("resource = ?", record.Resource)
	if excludeID != "" {
		query0 = query0.Where("id <> ?", excludeID)
	}
	var count0 int64
	if err := query0.Count(&count0).Error; err != nil {
		return false, err
	}
	if count0 > 0 {
		return true, nil
	}
	return false, nil
}

func boolValue(value *bool) bool {
	return value != nil && *value
}

func escapeLike(value string) string {
	value = strings.ReplaceAll(value, `!`, `!!`)
	value = strings.ReplaceAll(value, `%`, `!%`)
	return strings.ReplaceAll(value, `_`, `!_`)
}

func csvSafe(value string) string {
	if value == "" {
		return value
	}
	switch value[0] {
	case '=', '+', '-', '@':
		return "'" + value
	default:
		return value
	}
}
