// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/legacy-migration-checkpoints.yaml. DO NOT EDIT.

package legacycheckpoint

import (
	"context"
	"errors"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

type collectingLegacyMigrationCheckpointEvents struct {
	mu        sync.Mutex
	db        *gorm.DB
	events    []DomainEvent
	committed []bool
}

func (collector *collectingLegacyMigrationCheckpointEvents) Collect(_ context.Context, event DomainEvent) {
	var count int64
	resourceID := ""
	switch typed := event.(type) {
	case LegacyMigrationCheckpointCreatedEvent:
		resourceID = typed.ResourceID
	case LegacyMigrationCheckpointUpdatedEvent:
		resourceID = typed.ResourceID
	}
	committed := collector.db.Model(new(LegacyMigrationCheckpoint)).Where("id = ?", resourceID).Count(&count).Error == nil && count == 1
	collector.mu.Lock()
	defer collector.mu.Unlock()
	collector.events = append(collector.events, event)
	collector.committed = append(collector.committed, committed)
}

func (collector *collectingLegacyMigrationCheckpointEvents) snapshot() ([]DomainEvent, []bool) {
	collector.mu.Lock()
	defer collector.mu.Unlock()
	return append([]DomainEvent(nil), collector.events...), append([]bool(nil), collector.committed...)
}

func TestLegacyMigrationCheckpointServiceCRUDQueryExportAndPostCommitEvents(t *testing.T) {
	db := openLegacyMigrationCheckpointTestDatabase(t)
	if _, err := NewService(db, nil); err == nil {
		t.Fatal("NewService(nil event collector) unexpectedly succeeded")
	}
	var typedNilCollector *collectingLegacyMigrationCheckpointEvents
	if _, err := NewService(db, typedNilCollector); err == nil {
		t.Fatal("NewService(typed nil event collector) unexpectedly succeeded")
	}
	collector := &collectingLegacyMigrationCheckpointEvents{db: db}
	service, err := NewService(db, collector)
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}

	invalid := validLegacyMigrationCheckpointInput()
	invalid.Resource = "invalid value"
	if _, err := service.Create(context.Background(), invalid); err == nil {
		t.Fatal("Create(invalid pattern) unexpectedly succeeded")
	}

	input := validLegacyMigrationCheckpointInput()
	created, err := service.Create(context.Background(), input)
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if created.ID == "" {
		t.Fatal("Create() did not assign an ID")
	}
	if created.State != "inventoried" {
		t.Fatalf("default state = %q", created.State)
	}
	if created.ReleaseBlocking != true {
		t.Fatalf("default releaseBlocking = %v", created.ReleaseBlocking)
	}
	events, committed := collector.snapshot()
	if len(events) != 1 || events[0].EventName() != "platform.legacycheckpoint.created" || !committed[0] {
		t.Fatalf("created events = %#v, committed = %#v", events, committed)
	}
	if _, err := service.Create(context.Background(), validLegacyMigrationCheckpointInput()); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
		t.Fatalf("Create(duplicate) error = %v, want conflict", err)
	}

	secondInput := validLegacyMigrationCheckpointInput()
	secondInput.Resource = "VALUE_02"
	secondInput.Owner = "VALUE_02"
	secondInput.Evidence = "VALUE_02"
	second, err := service.Create(context.Background(), secondInput)
	if err != nil {
		t.Fatalf("Create(second) error = %v", err)
	}
	if err := db.Exec("CREATE UNIQUE INDEX ux_legacycheckpoint_generated_update_conflict ON biz_legacy_migration_checkpoints (owner)").Error; err != nil {
		t.Fatalf("create update conflict index: %v", err)
	}
	conflictingValue := second.Owner
	if _, err := service.Update(context.Background(), created.ID, &UpdateLegacyMigrationCheckpointInput{Owner: &conflictingValue}); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
		t.Fatalf("Update(duplicate without TranslateError) error = %v, want conflict", err)
	}
	if err := db.Exec("DROP INDEX ux_legacycheckpoint_generated_update_conflict").Error; err != nil {
		t.Fatalf("drop update conflict index: %v", err)
	}
	conflictingUniqueValue := second.Resource
	if _, err := service.Update(context.Background(), created.ID, &UpdateLegacyMigrationCheckpointInput{Resource: &conflictingUniqueValue}); !errors.Is(err, ErrLegacyMigrationCheckpointConflict) {
		t.Fatalf("Update(declared duplicate without TranslateError) error = %v, want conflict", err)
	}

	query := ListLegacyMigrationCheckpointQuery{
		Current:         1,
		PageSize:        1,
		SortBy:          "resource",
		SortOrder:       "asc",
		Q:               input.Resource,
		Owner:           input.Owner,
		State:           input.State,
		ReleaseBlocking: input.ReleaseBlocking,
	}
	page, err := service.List(context.Background(), query)
	if err != nil {
		t.Fatalf("List() error = %v", err)
	}
	if page.Total != 1 || len(page.Data) != 1 || page.Data[0].ID != created.ID {
		t.Fatalf("List() = %#v", page)
	}
	updatedValue := "VALUE_02"
	updated, err := service.Update(context.Background(), created.ID, &UpdateLegacyMigrationCheckpointInput{Owner: &updatedValue})
	if err != nil {
		t.Fatalf("Update() error = %v", err)
	}
	if updated.Owner != updatedValue {
		t.Fatalf("updated owner = %q", updated.Owner)
	}
	events, committed = collector.snapshot()
	if events[len(events)-1].EventName() != "platform.legacycheckpoint.updated" || !committed[len(committed)-1] {
		t.Fatalf("updated events = %#v, committed = %#v", events, committed)
	}

	var exported strings.Builder
	if err := service.Export(context.Background(), ListLegacyMigrationCheckpointQuery{}, &exported); err != nil {
		t.Fatalf("Export() error = %v", err)
	}
	if !strings.Contains(exported.String(), "id,") || !strings.Contains(exported.String(), created.ID) {
		t.Fatalf("Export() = %q", exported.String())
	}
	if got := csvSafe("=SUM(A1:A2)"); got != "'=SUM(A1:A2)" {
		t.Fatalf("csvSafe() = %q", got)
	}

	if err := service.Delete(context.Background(), second.ID); err != nil {
		t.Fatalf("Delete() error = %v", err)
	}
	if _, err := service.Get(context.Background(), second.ID); !errors.Is(err, ErrLegacyMigrationCheckpointNotFound) {
		t.Fatalf("Get(deleted) error = %v, want not found", err)
	}
}

func validLegacyMigrationCheckpointInput() *CreateLegacyMigrationCheckpointInput {
	return &CreateLegacyMigrationCheckpointInput{
		Resource: "VALUE_01",
		Owner:    "VALUE_01",
		Evidence: "VALUE_01",
	}
}

func testBool(value bool) *bool { return &value }

func openLegacyMigrationCheckpointTestDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "legacycheckpoint.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareLegacyMigrationCheckpointAuthorizationTestSchema(t, db)
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("MigrateContext() error = %v", err)
	}
	return db
}
