// Code generated by mss application template v1.3.6. DO NOT EDIT.

// Package all returns every enabled business module in stable generation order.
package all

import "github.com/mss-boot-io/mss-boot-admin/admin/business"

// Modules returns a new slice so callers cannot mutate the generated registry.
func Modules() []business.Module {
	return []business.Module{}
}
