// Code generated by mss module template 1.3.0-frontend-v6.6 sync. DO NOT EDIT.

export default [
  {
    path: "/tenants",
    name: "tenant",
    icon: "table",
    component: "./generated/Tenant",
    access: 'canAccessRoute',
    permission: "/tenants",
  },
];
