// Code generated by mss application template v1.3.6. DO NOT EDIT.

import type { RouteRegistration } from '@mss-boot-io/admin-web/runtime';
import customRouteRegistrations from './business/route-registrations';
import generatedRouteRegistrations from './generated/routes';

function assertUniqueRouteRegistrations(registrations: readonly RouteRegistration[]): void {
  const uiPaths = new Set<string>();
  const serverPaths = new Set<string>();

  for (const registration of registrations) {
    if (uiPaths.has(registration.path)) {
      throw new Error(`duplicate business UI route path: ${registration.path}`);
    }
    uiPaths.add(registration.path);

    for (const serverPath of registration.serverPaths) {
      if (serverPaths.has(serverPath)) {
        throw new Error(`duplicate business server route path: ${serverPath}`);
      }
      serverPaths.add(serverPath);
    }
  }
}

const routeRegistrations: readonly RouteRegistration[] = [
  ...generatedRouteRegistrations,
  ...customRouteRegistrations,
];

assertUniqueRouteRegistrations(routeRegistrations);

export default routeRegistrations;
