// Code generated by mss application template v1.3.6. DO NOT EDIT.

import coreMessages from '@mss-boot-io/admin-web/runtime/locales/en-US';
import customMessages from '../business/locales/en-US';
import generatedMessages from '../generated/locales/en-US';

export default {
  ...coreMessages,
  ...generatedMessages,
  ...customMessages,
};
