// Code generated by mss application template v1.3.7. DO NOT EDIT.

import coreMessages from '@mss-boot-io/admin-web/runtime/locales/zh-CN';
import customMessages from '../business/locales/zh-CN';
import generatedMessages from '../generated/locales/zh-CN';

export default {
  ...coreMessages,
  ...generatedMessages,
  ...customMessages,
};
