// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"bytes"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"sync"
	"testing"

	"github.com/gin-gonic/gin"
)

type recordingTenantAuthorizer struct {
	mu          sync.Mutex
	denied      bool
	permissions []string
}

func (authorizer *recordingTenantAuthorizer) Authorize(_ *gin.Context, permission string) error {
	authorizer.mu.Lock()
	defer authorizer.mu.Unlock()
	authorizer.permissions = append(authorizer.permissions, permission)
	if authorizer.denied {
		return errors.New("denied")
	}
	return nil
}

func TestTenantRegisterRoutesFailsClosedWithoutAuthorizer(t *testing.T) {
	gin.SetMode(gin.TestMode)
	router := gin.New()
	service, err := NewService(openTenantTestDatabase(t), discardEventCollector{})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}
	if err := RegisterRoutes(router.Group("/admin/api"), service, nil); err == nil {
		t.Fatal("RegisterRoutes(nil authorizer) unexpectedly succeeded")
	}
	var typedNilAuthorizer *recordingTenantAuthorizer
	if err := RegisterRoutes(router.Group("/admin/api"), service, typedNilAuthorizer); err == nil {
		t.Fatal("RegisterRoutes(typed nil authorizer) unexpectedly succeeded")
	}
	if routes := router.Routes(); len(routes) != 0 {
		t.Fatalf("routes mounted before authorization was available: %#v", routes)
	}
}

func TestTenantEveryDeclaredOperationIsBackendAuthorized(t *testing.T) {
	gin.SetMode(gin.TestMode)
	service, err := NewService(openTenantTestDatabase(t), discardEventCollector{})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}
	authorizer := &recordingTenantAuthorizer{denied: true}
	router := gin.New()
	if err := RegisterRoutes(router.Group("/admin/api"), service, authorizer); err != nil {
		t.Fatalf("RegisterRoutes() error = %v", err)
	}
	cases := []struct {
		operation  string
		method     string
		path       string
		permission string
	}{
		{operation: "create", method: "POST", path: "/admin/api/tenants", permission: PermissionCreate},
		{operation: "delete", method: "DELETE", path: "/admin/api/tenants/:id", permission: PermissionDelete},
		{operation: "export", method: "GET", path: "/admin/api/tenants/export", permission: PermissionExport},
		{operation: "get", method: "GET", path: "/admin/api/tenants/:id", permission: PermissionRead},
		{operation: "list", method: "GET", path: "/admin/api/tenants", permission: PermissionList},
		{operation: "update", method: "PUT", path: "/admin/api/tenants/:id", permission: PermissionUpdate},
	}
	for _, test := range cases {
		requestPath := strings.ReplaceAll(test.path, ":id", "record-id")
		response := performTenantRequest(router, test.method, requestPath, nil)
		if response.Code != http.StatusForbidden {
			t.Fatalf("%s authorization response = %d, want %d", test.operation, response.Code, http.StatusForbidden)
		}
	}
	authorizer.mu.Lock()
	got := append([]string(nil), authorizer.permissions...)
	authorizer.mu.Unlock()
	if len(got) != len(cases) {
		t.Fatalf("authorization calls = %v, want %d", got, len(cases))
	}
	for index, test := range cases {
		if got[index] != test.permission {
			t.Fatalf("authorization call %d = %q, want %q", index, got[index], test.permission)
		}
	}
}

func TestTenantHTTPAuthorizationValidationAndDeclaredOperations(t *testing.T) {
	gin.SetMode(gin.TestMode)
	db := openTenantTestDatabase(t)
	service, err := NewService(db, discardEventCollector{})
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}
	authorizer := &recordingTenantAuthorizer{denied: true}
	router := gin.New()
	if err := RegisterRoutes(router.Group("/admin/api"), service, authorizer); err != nil {
		t.Fatalf("RegisterRoutes() error = %v", err)
	}
	if got, want := len(router.Routes()), 6; got != want {
		t.Fatalf("registered routes = %d, want %d", got, want)
	}

	body, err := json.Marshal(validTenantInput())
	if err != nil {
		t.Fatalf("marshal input: %v", err)
	}
	denied := performTenantRequest(router, http.MethodPost, "/admin/api/tenants", body)
	if denied.Code != http.StatusForbidden || !strings.Contains(denied.Body.String(), "forbidden") {
		t.Fatalf("denied response = %d %q", denied.Code, denied.Body.String())
	}
	var count int64
	if err := db.Model(new(Tenant)).Count(&count).Error; err != nil || count != 0 {
		t.Fatalf("denied request mutated database: count=%d err=%v", count, err)
	}

	authorizer.mu.Lock()
	authorizer.denied = false
	authorizer.mu.Unlock()
	createdResponse := performTenantRequest(router, http.MethodPost, "/admin/api/tenants", body)
	if createdResponse.Code != http.StatusCreated {
		t.Fatalf("create response = %d %q", createdResponse.Code, createdResponse.Body.String())
	}
	var created Tenant
	if err := json.Unmarshal(createdResponse.Body.Bytes(), &created); err != nil || created.ID == "" {
		t.Fatalf("decode created response: record=%#v err=%v", created, err)
	}

	unknown := append(bytes.TrimSuffix(body, []byte("}")), []byte(",\"unknown\":true}")...)
	unknownResponse := performTenantRequest(router, http.MethodPost, "/admin/api/tenants", unknown)
	if unknownResponse.Code != http.StatusUnprocessableEntity || strings.Contains(unknownResponse.Body.String(), "unknown") {
		t.Fatalf("unknown-field response = %d %q", unknownResponse.Code, unknownResponse.Body.String())
	}

	listResponse := performTenantRequest(router, http.MethodGet, "/admin/api/tenants?current=1&pageSize=20", nil)
	if listResponse.Code != http.StatusOK || !strings.Contains(listResponse.Body.String(), created.ID) {
		t.Fatalf("list response = %d %q", listResponse.Code, listResponse.Body.String())
	}
	exportResponse := performTenantRequest(router, http.MethodGet, "/admin/api/tenants/export", nil)
	if exportResponse.Code != http.StatusOK || !strings.Contains(exportResponse.Header().Get("Content-Type"), "text/csv") {
		t.Fatalf("export response = %d %q", exportResponse.Code, exportResponse.Body.String())
	}
}

func performTenantRequest(handler http.Handler, method, path string, body []byte) *httptest.ResponseRecorder {
	request := httptest.NewRequest(method, path, bytes.NewReader(body))
	if body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	response := httptest.NewRecorder()
	handler.ServeHTTP(response, request)
	return response
}
