// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"github.com/mss-boot-io/mss-boot-admin/admin/business"
)

// Descriptor returns this module's immutable metadata projection.
func Descriptor() business.Descriptor {
	return business.Descriptor{
		Name:        "tenant",
		DisplayName: "租户",
		Description: "Manage tenant desired state and public storefront bindings. Delete only archives the control record; resource provisioning and destruction remain outside this module.",
		Version:     "v1alpha1",
		Model:       new(Tenant),
		Permissions: []business.Permission{
			{
				Code:         "tenant:create",
				DisplayName:  "Create Tenant",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "tenant:delete",
				DisplayName:  "Archive Tenant Record",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "tenant:export",
				DisplayName:  "Export Tenant",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "tenant:list",
				DisplayName:  "List Tenant",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "tenant:read",
				DisplayName:  "Read Tenant",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
			{
				Code:         "tenant:update",
				DisplayName:  "Update Tenant",
				Description:  "",
				DefaultRoles: []string{"admin"},
			},
		},
		Menu: business.Menu{
			Path:          "/tenants",
			DisplayName:   "租户管理",
			DisplayNameEn: "Tenants",
			Icon:          "table",
			Parent:        "",
			Order:         0,
			Hidden:        false,
		},
	}
}
