// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"fmt"
	"regexp"
	"strings"
	"unicode/utf8"
)

// ValidationError is a value-redacted, field-specific input failure.
type ValidationError struct {
	Field string `json:"field"`
	Rule  string `json:"rule"`
}

func (e *ValidationError) Error() string {
	return fmt.Sprintf("invalid %s: %s", e.Field, e.Rule)
}

// CreateTenantInput is the authoritative create contract.
type CreateTenantInput struct {
	DisplayName      string `json:"displayName"`
	Slug             string `json:"slug"`
	DesiredServing   *bool  `json:"desiredServing"`
	H5Host           string `json:"h5Host"`
	WechatAppID      string `json:"wechatAppId"`
	DefaultLocaleKey string `json:"defaultLocaleKey"`
	DefaultCurrency  string `json:"defaultCurrency"`
	TimeZone         string `json:"timeZone"`
}

// UpdateTenantInput is a presence-aware partial update contract.
type UpdateTenantInput struct {
	DisplayName      *string `json:"displayName"`
	Slug             *string `json:"slug"`
	DesiredServing   *bool   `json:"desiredServing"`
	H5Host           *string `json:"h5Host"`
	WechatAppID      *string `json:"wechatAppId"`
	DefaultLocaleKey *string `json:"defaultLocaleKey"`
	DefaultCurrency  *string `json:"defaultCurrency"`
	TimeZone         *string `json:"timeZone"`
}

// ListTenantQuery defines bounded filtering, searching, sorting, and paging.
type ListTenantQuery struct {
	Q                string `form:"q" query:"q"`
	Current          int    `form:"current" query:"current"`
	PageSize         int    `form:"pageSize" query:"pageSize"`
	SortBy           string `form:"sortBy" query:"sortBy"`
	SortOrder        string `form:"sortOrder" query:"sortOrder"`
	DesiredServing   *bool  `form:"desiredServing" query:"desiredServing"`
	DefaultLocaleKey string `form:"defaultLocaleKey" query:"defaultLocaleKey"`
}

// TenantPage is the stable list response contract.
type TenantPage struct {
	Data     []Tenant `json:"data"`
	Total    int64    `json:"total"`
	Current  int      `json:"current"`
	PageSize int      `json:"pageSize"`
}

func (input *CreateTenantInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	input.DisplayName = strings.TrimSpace(input.DisplayName)
	if err := validateDisplayName(input.DisplayName, true); err != nil {
		return err
	}
	input.Slug = strings.TrimSpace(input.Slug)
	if err := validateSlug(input.Slug, true); err != nil {
		return err
	}
	if input.DesiredServing == nil {
		value := true
		input.DesiredServing = &value
	}
	if input.DesiredServing == nil {
		return &ValidationError{Field: "desiredServing", Rule: "required"}
	}
	input.H5Host = strings.TrimSpace(input.H5Host)
	if err := validateH5Host(input.H5Host, true); err != nil {
		return err
	}
	input.WechatAppID = strings.TrimSpace(input.WechatAppID)
	if err := validateWechatAppID(input.WechatAppID, false); err != nil {
		return err
	}
	input.DefaultLocaleKey = strings.TrimSpace(input.DefaultLocaleKey)
	if input.DefaultLocaleKey == "" {
		input.DefaultLocaleKey = "zh-cn"
	}
	if err := validateDefaultLocaleKey(input.DefaultLocaleKey, true); err != nil {
		return err
	}
	input.DefaultCurrency = strings.TrimSpace(input.DefaultCurrency)
	if err := validateDefaultCurrency(input.DefaultCurrency, true); err != nil {
		return err
	}
	input.TimeZone = strings.TrimSpace(input.TimeZone)
	if err := validateTimeZone(input.TimeZone, true); err != nil {
		return err
	}
	return nil
}

func (input *UpdateTenantInput) normalizeAndValidate() error {
	if input == nil {
		return &ValidationError{Field: "body", Rule: "required"}
	}
	changed := false
	if input.DisplayName != nil {
		changed = true
		normalized := strings.TrimSpace(*input.DisplayName)
		input.DisplayName = &normalized
		if err := validateDisplayName(normalized, true); err != nil {
			return err
		}
	}
	if input.Slug != nil {
		changed = true
		normalized := strings.TrimSpace(*input.Slug)
		input.Slug = &normalized
		if err := validateSlug(normalized, true); err != nil {
			return err
		}
	}
	if input.DesiredServing != nil {
		changed = true
	}
	if input.H5Host != nil {
		changed = true
		normalized := strings.TrimSpace(*input.H5Host)
		input.H5Host = &normalized
		if err := validateH5Host(normalized, true); err != nil {
			return err
		}
	}
	if input.WechatAppID != nil {
		changed = true
		normalized := strings.TrimSpace(*input.WechatAppID)
		input.WechatAppID = &normalized
		if err := validateWechatAppID(normalized, false); err != nil {
			return err
		}
	}
	if input.DefaultLocaleKey != nil {
		changed = true
		normalized := strings.TrimSpace(*input.DefaultLocaleKey)
		input.DefaultLocaleKey = &normalized
		if err := validateDefaultLocaleKey(normalized, true); err != nil {
			return err
		}
	}
	if input.DefaultCurrency != nil {
		changed = true
		normalized := strings.TrimSpace(*input.DefaultCurrency)
		input.DefaultCurrency = &normalized
		if err := validateDefaultCurrency(normalized, true); err != nil {
			return err
		}
	}
	if input.TimeZone != nil {
		changed = true
		normalized := strings.TrimSpace(*input.TimeZone)
		input.TimeZone = &normalized
		if err := validateTimeZone(normalized, true); err != nil {
			return err
		}
	}
	if !changed {
		return &ValidationError{Field: "body", Rule: "at-least-one-field"}
	}
	return nil
}

func (query *ListTenantQuery) normalizeAndValidate() error {
	if query == nil {
		return &ValidationError{Field: "query", Rule: "required"}
	}
	query.Q = strings.TrimSpace(query.Q)
	if query.Current <= 0 {
		query.Current = 1
	}
	if query.PageSize <= 0 {
		query.PageSize = 20
	}
	if query.PageSize > 100 {
		return &ValidationError{Field: "pageSize", Rule: "maximum-100"}
	}
	if query.SortOrder == "" {
		query.SortOrder = "asc"
	}
	if query.SortOrder != "asc" && query.SortOrder != "desc" {
		return &ValidationError{Field: "sortOrder", Rule: "asc-or-desc"}
	}
	if query.SortBy != "" {
		switch query.SortBy {
		case "displayName":
		case "slug":
		default:
			return &ValidationError{Field: "sortBy", Rule: "unsupported"}
		}
	}
	query.DefaultLocaleKey = strings.TrimSpace(query.DefaultLocaleKey)
	if query.DefaultLocaleKey != "" {
		if err := validateDefaultLocaleKey(query.DefaultLocaleKey, false); err != nil {
			return err
		}
	}
	return nil
}

func validateDisplayName(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "displayName", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 1 {
		return &ValidationError{Field: "displayName", Rule: "minimum-length-1"}
	}
	if utf8.RuneCountInString(value) > 200 {
		return &ValidationError{Field: "displayName", Rule: "maximum-length-200"}
	}
	return nil
}

var slugPattern = regexp.MustCompile("^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")

func validateSlug(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "slug", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 2 {
		return &ValidationError{Field: "slug", Rule: "minimum-length-2"}
	}
	if utf8.RuneCountInString(value) > 63 {
		return &ValidationError{Field: "slug", Rule: "maximum-length-63"}
	}
	if !slugPattern.MatchString(value) {
		return &ValidationError{Field: "slug", Rule: "pattern"}
	}
	return nil
}

func validateH5Host(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "h5Host", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 1 {
		return &ValidationError{Field: "h5Host", Rule: "minimum-length-1"}
	}
	if utf8.RuneCountInString(value) > 253 {
		return &ValidationError{Field: "h5Host", Rule: "maximum-length-253"}
	}
	return nil
}

func validateWechatAppID(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "wechatAppId", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) > 64 {
		return &ValidationError{Field: "wechatAppId", Rule: "maximum-length-64"}
	}
	return nil
}

func validateDefaultLocaleKey(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "defaultLocaleKey", Rule: "required"}
		}
		return nil
	}
	switch value {
	case "zh-cn":
	case "en-us":
	default:
		return &ValidationError{Field: "defaultLocaleKey", Rule: "enum"}
	}
	return nil
}

var defaultCurrencyPattern = regexp.MustCompile("^[A-Z]{3}$")

func validateDefaultCurrency(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "defaultCurrency", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 3 {
		return &ValidationError{Field: "defaultCurrency", Rule: "minimum-length-3"}
	}
	if utf8.RuneCountInString(value) > 3 {
		return &ValidationError{Field: "defaultCurrency", Rule: "maximum-length-3"}
	}
	if !defaultCurrencyPattern.MatchString(value) {
		return &ValidationError{Field: "defaultCurrency", Rule: "pattern"}
	}
	return nil
}

func validateTimeZone(value string, required bool) error {
	if value == "" {
		if required {
			return &ValidationError{Field: "timeZone", Rule: "required"}
		}
		return nil
	}
	if utf8.RuneCountInString(value) < 1 {
		return &ValidationError{Field: "timeZone", Rule: "minimum-length-1"}
	}
	if utf8.RuneCountInString(value) > 64 {
		return &ValidationError{Field: "timeZone", Rule: "maximum-length-64"}
	}
	return nil
}
