// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"context"
	"time"
)

// DomainEvent is the narrow typed event boundary for this module checkpoint.
// It is intentionally not coupled to the v1.1 EventBus work.
type DomainEvent interface {
	EventName() string
}

// EventCollector receives typed events after the database transaction commits.
type EventCollector interface {
	Collect(context.Context, DomainEvent)
}

type discardEventCollector struct{}

func (discardEventCollector) Collect(context.Context, DomainEvent) {}

// TenantCreatedEvent is emitted for platform.tenant.created.
type TenantCreatedEvent struct {
	ResourceID string    `json:"resourceID"`
	OccurredAt time.Time `json:"occurredAt"`
}

func (TenantCreatedEvent) EventName() string { return "platform.tenant.created" }

// TenantUpdatedEvent is emitted for platform.tenant.updated.
type TenantUpdatedEvent struct {
	ResourceID    string    `json:"resourceID"`
	ChangedFields []string  `json:"changedFields"`
	OccurredAt    time.Time `json:"occurredAt"`
}

func (TenantUpdatedEvent) EventName() string { return "platform.tenant.updated" }
