// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func TestTenantForwardMigrationFreshRepeatAndConstraints(t *testing.T) {
	db := openUnmigratedTenantDatabase(t)
	runner := configuredTenantMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("fresh migration error = %v", err)
	}
	assertTenantSchemaReady(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("repeat migration error = %v", err)
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", TenantMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count migration versions: %v", err)
	}
	if versions != 1 {
		t.Fatalf("migration version rows = %d, want 1", versions)
	}
	invalidDefaultLocaleKey := &Tenant{
		DisplayName:      "VALUE_01",
		Slug:             "value",
		DesiredServing:   true,
		H5Host:           "VALUE_01",
		WechatAppID:      "VALUE_01",
		DefaultLocaleKey: "outside-contract",
		DefaultCurrency:  "VAL",
		TimeZone:         "VALUE_01",
	}
	if err := db.Create(invalidDefaultLocaleKey).Error; err == nil {
		t.Fatal("database enum constraint accepted an undeclared value")
	}
}

func TestTenantForwardMigrationPreservesUpgradeData(t *testing.T) {
	db := openUnmigratedTenantDatabase(t)
	if err := db.Exec("CREATE TABLE legacy_records (id TEXT PRIMARY KEY, value TEXT NOT NULL)").Error; err != nil {
		t.Fatalf("create legacy table: %v", err)
	}
	if err := db.Exec("INSERT INTO legacy_records (id, value) VALUES (?, ?)", "legacy-1", "preserve-me").Error; err != nil {
		t.Fatalf("insert legacy row: %v", err)
	}
	runner := configuredTenantMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("upgrade migration error = %v", err)
	}
	var value string
	if err := db.Raw("SELECT value FROM legacy_records WHERE id = ?", "legacy-1").Scan(&value).Error; err != nil {
		t.Fatalf("read legacy row: %v", err)
	}
	if value != "preserve-me" {
		t.Fatalf("legacy value = %q", value)
	}
	assertTenantSchemaReady(t, db)
}

func TestTenantForwardMigrationRecoversAfterInterruptionWithoutPartialTruth(t *testing.T) {
	db := openUnmigratedTenantDatabase(t)
	injected := errors.New("injected interruption")
	err := applyTenantMigration(db, TenantMigrationID.String(), func() error { return injected })
	if !errors.Is(err, injected) {
		t.Fatalf("interrupted migration error = %v", err)
	}
	if !db.Migrator().HasTable(new(Tenant)) {
		t.Fatal("interrupted migration did not reach the table checkpoint")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", TenantMigrationID.String()).Count(&versions).Error; err != nil {
		t.Fatalf("count interrupted version rows: %v", err)
	}
	if versions != 0 {
		t.Fatalf("interrupted migration recorded completion: %d", versions)
	}
	runner := configuredTenantMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("recovery migration error = %v", err)
	}
	assertTenantSchemaReady(t, db)
}

func TestTenantForwardMigrationRejectsExistingColumnShapeDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedTenantDatabase(t)
	driftedDDL, ok := driftTenantSQLiteColumnType(createTenantTableDDL["sqlite"])
	if !ok {
		t.Fatal("test contract could not select a business column to corrupt")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create drifted table: %v", err)
	}
	runner := configuredTenantMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing column shape")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", TenantMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func TestTenantForwardMigrationRejectsNullableRequiredColumnsWithoutVersionTruth(t *testing.T) {
	t.Run("display_name", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "display_name")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("slug", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "slug")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("desired_serving", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "desired_serving")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("h5_host", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "h5_host")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("default_locale_key", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "default_locale_key")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("default_currency", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "default_currency")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
	t.Run("time_zone", func(t *testing.T) {
		db := openUnmigratedTenantDatabase(t)
		driftedDDL, ok := driftTenantSQLiteRequiredColumnNullable(createTenantTableDDL["sqlite"], "time_zone")
		if !ok {
			t.Fatal("test contract could not make the required column nullable")
		}
		if err := db.Exec(driftedDDL).Error; err != nil {
			t.Fatalf("create nullable-column table: %v", err)
		}
		runner := configuredTenantMigrationRunner(t, db)
		if err := runner.MigrateContext(context.Background()); err == nil {
			t.Fatal("migration accepted an incompatible nullable required column")
		}
		assertTenantMigrationVersionAbsent(t, db)
	})
}

func TestTenantForwardMigrationRejectsIndexShapeDriftWithoutVersionTruth(t *testing.T) {
	for _, test := range []struct {
		name       string
		wrongIndex func(tenantMigrationIndex) string
	}{
		{
			name: "columns",
			wrongIndex: func(index tenantMigrationIndex) string {
				keyword := ""
				if index.unique {
					keyword = "UNIQUE "
				}
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_tenants\" (\"id\")"
			},
		},
		{
			name: "uniqueness",
			wrongIndex: func(index tenantMigrationIndex) string {
				keyword := "UNIQUE "
				if index.unique {
					keyword = ""
				}
				columns := "\"" + strings.Join(index.columns, "\", \"") + "\""
				return "CREATE " + keyword + "INDEX \"" + index.name + "\" ON \"biz_tenants\" (" + columns + ")"
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			db := openUnmigratedTenantDatabase(t)
			if err := db.Exec(createTenantTableDDL["sqlite"]).Error; err != nil {
				t.Fatalf("create table: %v", err)
			}
			if len(tenantMigrationIndexes) == 0 {
				t.Fatal("test contract requires an index")
			}
			if err := db.Exec(test.wrongIndex(tenantMigrationIndexes[0])).Error; err != nil {
				t.Fatalf("create wrong-shape index: %v", err)
			}
			runner := configuredTenantMigrationRunner(t, db)
			if err := runner.MigrateContext(context.Background()); err == nil {
				t.Fatal("migration accepted an incompatible same-name index")
			}
			assertTenantMigrationVersionAbsent(t, db)
		})
	}
}

func TestTenantGeneratedMigrationDuplicateRegistrationFailsPreflightWithoutDatabase(t *testing.T) {
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("first RegisterMigration() error = %v", err)
	}
	if err := RegisterMigration(runner); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("duplicate RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("ValidateRegistrations() error = %v, want duplicate ID", err)
	}
	if runner.GetDb() != nil {
		t.Fatal("registration preflight unexpectedly required a database")
	}
}

func TestTenantForwardMigrationRejectsExistingCheckBodyDriftWithoutVersionTruth(t *testing.T) {
	db := openUnmigratedTenantDatabase(t)
	originalValue := "'" + "zh-cn" + "'"
	driftedDDL := strings.Replace(createTenantTableDDL["sqlite"], originalValue, "'contract-drift'", 1)
	if driftedDDL == createTenantTableDDL["sqlite"] {
		t.Fatal("test contract could not corrupt the check body")
	}
	if err := db.Exec(driftedDDL).Error; err != nil {
		t.Fatalf("create check-drifted table: %v", err)
	}
	runner := configuredTenantMigrationRunner(t, db)
	if err := runner.MigrateContext(context.Background()); err == nil {
		t.Fatal("migration accepted an incompatible existing check body")
	}
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", TenantMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("check-drifted migration version count = %d, err=%v", versions, err)
	}
}

func driftTenantSQLiteColumnType(ddl string) (string, bool) {
	for _, column := range tenantMigrationColumns[4:] {
		var declaredType string
		if column.length > 0 {
			declaredType = fmt.Sprintf("VARCHAR(%d)", column.length)
		} else {
			declaredType = "BOOLEAN"
		}
		original := fmt.Sprintf("%q %s", column.name, declaredType)
		replacement := fmt.Sprintf("%q BLOB", column.name)
		if drifted := strings.Replace(ddl, original, replacement, 1); drifted != ddl {
			return drifted, true
		}
	}
	return ddl, false
}

func driftTenantSQLiteRequiredColumnNullable(ddl, column string) (string, bool) {
	token := fmt.Sprintf("%q", column)
	for _, line := range strings.SplitAfter(ddl, "\n") {
		if !strings.Contains(line, token) || !strings.Contains(line, " NOT NULL") {
			continue
		}
		driftedLine := strings.Replace(line, " NOT NULL", "", 1)
		return strings.Replace(ddl, line, driftedLine, 1), true
	}
	return ddl, false
}

func assertTenantMigrationVersionAbsent(t *testing.T, db *gorm.DB) {
	t.Helper()
	var versions int64
	if err := db.Model(new(migrationmodels.Migration)).Where("version = ?", TenantMigrationID.String()).Count(&versions).Error; err != nil || versions != 0 {
		t.Fatalf("drifted migration version count = %d, err=%v", versions, err)
	}
}

func openUnmigratedTenantDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "migration.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareTenantAuthorizationTestSchema(t, db)
	return db
}

func configuredTenantMigrationRunner(t *testing.T, db *gorm.DB) *migration.Migration {
	t.Helper()
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	if err := runner.ValidateRegistrations(); err != nil {
		t.Fatalf("ValidateRegistrations() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	return runner
}

func assertTenantSchemaReady(t *testing.T, db *gorm.DB) {
	t.Helper()
	if err := verifyTenantSchema(db); err != nil {
		t.Fatalf("schema readiness error = %v", err)
	}
	if !db.Migrator().HasIndex(new(Tenant), "idx_biz_tenants_deleted_at") {
		t.Fatal("missing index idx_biz_tenants_deleted_at")
	}
	if !db.Migrator().HasIndex(new(Tenant), "ux_biz_tenants_h5_host") {
		t.Fatal("missing index ux_biz_tenants_h5_host")
	}
	if !db.Migrator().HasIndex(new(Tenant), "ux_biz_tenants_slug") {
		t.Fatal("missing index ux_biz_tenants_slug")
	}
}
