// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const TenantMigrationID migration.MigrationID = "66966149766766"

var createTenantTableDDL = map[string]string{
	"sqlite":   "CREATE TABLE IF NOT EXISTS \"biz_tenants\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" DATETIME NOT NULL,\n  \"updated_at\" DATETIME NOT NULL,\n  \"deleted_at\" DATETIME NULL,\n  \"display_name\" VARCHAR(200) NOT NULL,\n  \"slug\" VARCHAR(63) NOT NULL,\n  \"desired_serving\" BOOLEAN NOT NULL DEFAULT 1,\n  \"h5_host\" VARCHAR(253) NOT NULL,\n  \"wechat_app_id\" VARCHAR(64),\n  \"default_locale_key\" VARCHAR(255) NOT NULL DEFAULT 'zh-cn',\n  \"default_currency\" VARCHAR(3) NOT NULL,\n  \"time_zone\" VARCHAR(64) NOT NULL,\n  CONSTRAINT \"ck_biz_tenants_default_locale_key\" CHECK (\"default_locale_key\" IN ('zh-cn', 'en-us'))\n)",
	"postgres": "CREATE TABLE IF NOT EXISTS \"biz_tenants\" (\n  \"id\" VARCHAR(64) NOT NULL PRIMARY KEY,\n  \"created_at\" TIMESTAMPTZ NOT NULL,\n  \"updated_at\" TIMESTAMPTZ NOT NULL,\n  \"deleted_at\" TIMESTAMPTZ NULL,\n  \"display_name\" VARCHAR(200) NOT NULL,\n  \"slug\" VARCHAR(63) NOT NULL,\n  \"desired_serving\" BOOLEAN NOT NULL DEFAULT TRUE,\n  \"h5_host\" VARCHAR(253) NOT NULL,\n  \"wechat_app_id\" VARCHAR(64),\n  \"default_locale_key\" VARCHAR(255) NOT NULL DEFAULT 'zh-cn',\n  \"default_currency\" VARCHAR(3) NOT NULL,\n  \"time_zone\" VARCHAR(64) NOT NULL,\n  CONSTRAINT \"ck_biz_tenants_default_locale_key\" CHECK (\"default_locale_key\" IN ('zh-cn', 'en-us'))\n)",
	"mysql":    "CREATE TABLE IF NOT EXISTS `biz_tenants` (\n  `id` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,\n  `created_at` DATETIME(3) NOT NULL,\n  `updated_at` DATETIME(3) NOT NULL,\n  `deleted_at` DATETIME(3) NULL,\n  `display_name` VARCHAR(200) COLLATE utf8mb4_bin NOT NULL,\n  `slug` VARCHAR(63) COLLATE utf8mb4_bin NOT NULL,\n  `desired_serving` BOOLEAN NOT NULL DEFAULT TRUE,\n  `h5_host` VARCHAR(253) COLLATE utf8mb4_bin NOT NULL,\n  `wechat_app_id` VARCHAR(64) COLLATE utf8mb4_bin,\n  `default_locale_key` VARCHAR(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'zh-cn',\n  `default_currency` VARCHAR(3) COLLATE utf8mb4_bin NOT NULL,\n  `time_zone` VARCHAR(64) COLLATE utf8mb4_bin NOT NULL,\n  CONSTRAINT `ck_biz_tenants_default_locale_key` CHECK (`default_locale_key` IN ('zh-cn', 'en-us'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin",
}

type tenantMigrationColumn struct {
	name          string
	databaseTypes map[string]string
	nullable      bool
	primaryKey    bool
	length        int64
	hasDefault    bool
	defaultValue  string
}

var tenantMigrationColumns = []tenantMigrationColumn{
	{
		name: "id",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   true,
		length:       64,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "created_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "updated_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "deleted_at",
		databaseTypes: map[string]string{
			"sqlite":   "datetime",
			"postgres": "timestamptz",
			"mysql":    "datetime",
		},
		nullable:     true,
		primaryKey:   false,
		length:       0,
		hasDefault:   false,
		defaultValue: "",
	},
	{
		name: "display_name",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       200,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "slug",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       63,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "desired_serving",
		databaseTypes: map[string]string{
			"sqlite":   "boolean|bool",
			"postgres": "bool|boolean",
			"mysql":    "tinyint|boolean|bool",
		},
		nullable:     false,
		primaryKey:   false,
		length:       0,
		hasDefault:   true,
		defaultValue: "true",
	},
	{
		name: "h5_host",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       253,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "wechat_app_id",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     true,
		primaryKey:   false,
		length:       64,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "default_locale_key",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       255,
		hasDefault:   true,
		defaultValue: "zh-cn",
	},
	{
		name: "default_currency",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       3,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
	{
		name: "time_zone",
		databaseTypes: map[string]string{
			"sqlite":   "varchar",
			"postgres": "varchar",
			"mysql":    "varchar",
		},
		nullable:     false,
		primaryKey:   false,
		length:       64,
		hasDefault:   false,
		defaultValue: "<nil>",
	},
}

type tenantMigrationIndex struct {
	name    string
	columns []string
	unique  bool
	ddl     map[string]string
}

var tenantMigrationIndexes = []tenantMigrationIndex{
	{
		name:    "idx_biz_tenants_deleted_at",
		columns: []string{"deleted_at"},
		unique:  false,
		ddl: map[string]string{
			"sqlite":   "CREATE INDEX IF NOT EXISTS \"idx_biz_tenants_deleted_at\" ON \"biz_tenants\" (\"deleted_at\")",
			"postgres": "CREATE INDEX IF NOT EXISTS \"idx_biz_tenants_deleted_at\" ON \"biz_tenants\" (\"deleted_at\")",
			"mysql":    "CREATE INDEX `idx_biz_tenants_deleted_at` ON `biz_tenants` (`deleted_at`)",
		},
	},
	{
		name:    "ux_biz_tenants_h5_host",
		columns: []string{"h5_host"},
		unique:  true,
		ddl: map[string]string{
			"sqlite":   "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_tenants_h5_host\" ON \"biz_tenants\" (\"h5_host\")",
			"postgres": "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_tenants_h5_host\" ON \"biz_tenants\" (\"h5_host\")",
			"mysql":    "CREATE UNIQUE INDEX `ux_biz_tenants_h5_host` ON `biz_tenants` (`h5_host`)",
		},
	},
	{
		name:    "ux_biz_tenants_slug",
		columns: []string{"slug"},
		unique:  true,
		ddl: map[string]string{
			"sqlite":   "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_tenants_slug\" ON \"biz_tenants\" (\"slug\")",
			"postgres": "CREATE UNIQUE INDEX IF NOT EXISTS \"ux_biz_tenants_slug\" ON \"biz_tenants\" (\"slug\")",
			"mysql":    "CREATE UNIQUE INDEX `ux_biz_tenants_slug` ON `biz_tenants` (`slug`)",
		},
	},
}

// RegisterMigration registers the complete lossless ID on an explicit runner.
func RegisterMigration(runner *migration.Migration) error {
	if runner == nil {
		return errors.New("tenant migration runner is required")
	}
	if err := runner.Register(TenantMigrationID, migrateTenant); err != nil {
		return err
	}
	return runner.Register(TenantAuthorizationMigrationID, migrateTenantAuthorization)
}

func migrateTenant(db *gorm.DB, version string) error {
	return applyTenantMigration(db, version, nil)
}

// applyTenantMigration is an additive, forward-only migration. The
// hook exists solely for deterministic interruption recovery tests.
func applyTenantMigration(db *gorm.DB, version string, afterTable func() error) error {
	if db == nil {
		return errors.New("tenant migration database is required")
	}
	if version != TenantMigrationID.String() {
		return errors.New("tenant migration version mismatch")
	}
	dialect := db.Dialector.Name()
	createDDL, supported := createTenantTableDDL[dialect]
	if !supported {
		return fmt.Errorf("tenant migration: unsupported database dialect %q", dialect)
	}
	if !db.Migrator().HasTable(new(Tenant)) {
		if err := db.Exec(createDDL).Error; err != nil {
			return errors.New("tenant migration: create table failed")
		}
	}
	if afterTable != nil {
		if err := afterTable(); err != nil {
			return fmt.Errorf("tenant migration interrupted after table creation: %w", err)
		}
	}
	for _, databaseIndex := range tenantMigrationIndexes {
		if db.Migrator().HasIndex(new(Tenant), databaseIndex.name) {
			continue
		}
		if err := db.Exec(databaseIndex.ddl[dialect]).Error; err != nil {
			return errors.New("tenant migration: create index failed")
		}
	}
	if err := verifyTenantSchema(db); err != nil {
		return err
	}
	versionRow := &migrationmodels.Migration{}
	versionRow.SetVersion(version)
	if err := db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "version"}},
		DoNothing: true,
	}).Create(versionRow).Error; err != nil {
		return errors.New("tenant migration: record version failed")
	}
	return nil
}

func verifyTenantSchema(db *gorm.DB) error {
	if !db.Migrator().HasTable(new(Tenant)) {
		return errors.New("tenant migration: table readiness failed")
	}
	columnTypes, err := db.Migrator().ColumnTypes(new(Tenant))
	if err != nil {
		return errors.New("tenant migration: column shape readiness failed")
	}
	columnsByName := make(map[string]gorm.ColumnType, len(columnTypes))
	for _, columnType := range columnTypes {
		columnsByName[columnType.Name()] = columnType
	}
	dialect := db.Dialector.Name()
	for _, expected := range tenantMigrationColumns {
		actual, ok := columnsByName[expected.name]
		if !ok || !migrationDatabaseTypeAllowed(expected.databaseTypes[dialect], actual.DatabaseTypeName()) {
			return errors.New("tenant migration: column shape readiness failed")
		}
		nullable, nullableKnown := actual.Nullable()
		if !nullableKnown || nullable != expected.nullable {
			return errors.New("tenant migration: column shape readiness failed")
		}
		primaryKey, primaryKeyKnown := actual.PrimaryKey()
		if !primaryKeyKnown || primaryKey != expected.primaryKey {
			return errors.New("tenant migration: column shape readiness failed")
		}
		if expected.length > 0 {
			length, lengthKnown := actual.Length()
			if !lengthKnown || length != expected.length {
				return errors.New("tenant migration: column shape readiness failed")
			}
		}
		defaultValue, hasDefault := actual.DefaultValue()
		if hasDefault != expected.hasDefault || (hasDefault && normalizeMigrationDefault(defaultValue) != normalizeMigrationDefault(expected.defaultValue)) {
			return errors.New("tenant migration: column shape readiness failed")
		}
	}
	for _, expected := range tenantMigrationIndexes {
		columns, unique, err := loadTenantMigrationIndexShape(db, dialect, expected.name)
		if err != nil || !migrationStringSlicesEqual(columns, expected.columns) || unique != expected.unique {
			return errors.New("tenant migration: index readiness failed")
		}
	}
	return verifyTenantChecks(db)
}

func loadTenantMigrationIndexShape(db *gorm.DB, dialect, name string) ([]string, bool, error) {
	rows := make([]struct {
		ColumnName string `gorm:"column:column_name"`
		IsUnique   bool   `gorm:"column:is_unique"`
	}, 0)
	var query string
	switch dialect {
	case "sqlite":
		query = "SELECT info.name AS column_name, list.\"unique\" <> 0 AS is_unique FROM pragma_index_list(?) AS list, pragma_index_info(list.name) AS info WHERE list.name = ? ORDER BY info.seqno"
	case "mysql":
		query = "SELECT column_name, non_unique = 0 AS is_unique FROM information_schema.statistics WHERE table_schema = DATABASE() AND table_name = ? AND index_name = ? ORDER BY seq_in_index"
	case "postgres":
		query = "SELECT attribute.attname AS column_name, catalog.indisunique AS is_unique FROM pg_index AS catalog JOIN pg_class AS table_class ON table_class.oid = catalog.indrelid JOIN pg_namespace AS namespace ON namespace.oid = table_class.relnamespace JOIN pg_class AS index_class ON index_class.oid = catalog.indexrelid JOIN LATERAL unnest(catalog.indkey) WITH ORDINALITY AS key(attnum, position) ON true JOIN pg_attribute AS attribute ON attribute.attrelid = table_class.oid AND attribute.attnum = key.attnum WHERE namespace.nspname = current_schema() AND table_class.relname = ? AND index_class.relname = ? ORDER BY key.position"
	default:
		return nil, false, errors.New("tenant migration: unsupported index dialect")
	}
	if err := db.Raw(query, "biz_tenants", name).Scan(&rows).Error; err != nil {
		return nil, false, err
	}
	if len(rows) == 0 {
		return nil, false, errors.New("tenant migration: index not found")
	}
	columns := make([]string, 0, len(rows))
	unique := rows[0].IsUnique
	for _, row := range rows {
		if row.IsUnique != unique {
			return nil, false, errors.New("tenant migration: inconsistent index metadata")
		}
		columns = append(columns, row.ColumnName)
	}
	return columns, unique, nil
}

func migrationStringSlicesEqual(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func migrationDatabaseTypeAllowed(allowed, actual string) bool {
	actual = strings.ToLower(strings.TrimSpace(actual))
	for _, candidate := range strings.Split(allowed, "|") {
		candidate = strings.ToLower(strings.TrimSpace(candidate))
		if actual == candidate || strings.HasPrefix(actual, candidate+"(") {
			return true
		}
	}
	return false
}

func normalizeMigrationDefault(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	for strings.HasPrefix(value, "(") && strings.HasSuffix(value, ")") {
		value = strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(value, "("), ")"))
	}
	if cast := strings.Index(value, "::"); cast >= 0 {
		value = value[:cast]
	}
	value = strings.Trim(strings.TrimSpace(value), "'\"")
	switch value {
	case "1", "b'1", "true":
		return "true"
	case "0", "b'0", "false":
		return "false"
	default:
		return value
	}
}

func verifyTenantChecks(db *gorm.DB) error {
	dialect := db.Dialector.Name()
	var definition string
	switch dialect {
	case "sqlite":
		if err := db.Raw("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", "biz_tenants").Scan(&definition).Error; err != nil {
			return errors.New("tenant migration: check readiness failed")
		}
		if !strings.Contains(definition, "ck_biz_tenants_default_locale_key") || !strings.Contains(normalizeMigrationCheckDefinition(definition), normalizeMigrationCheckDefinition("CHECK (\"default_locale_key\" IN ('zh-cn', 'en-us'))")) {
			return errors.New("tenant migration: check readiness failed")
		}
	case "postgres":
		if err := db.Raw("SELECT pg_get_constraintdef(oid) FROM pg_constraint WHERE conname = ? AND conrelid = ?::regclass", "ck_biz_tenants_default_locale_key", "biz_tenants").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("tenant migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("CHECK (((\"default_locale_key\")::text = ANY ((ARRAY['zh-cn'::character varying, 'en-us'::character varying])::text[])))") {
			return errors.New("tenant migration: check shape readiness failed")
		}
	case "mysql":
		if err := db.Raw("SELECT cc.check_clause FROM information_schema.check_constraints AS cc JOIN information_schema.table_constraints AS tc ON tc.constraint_schema = cc.constraint_schema AND tc.constraint_name = cc.constraint_name WHERE tc.constraint_schema = DATABASE() AND tc.table_name = ? AND tc.constraint_name = ? AND tc.constraint_type = 'CHECK'", "biz_tenants", "ck_biz_tenants_default_locale_key").Scan(&definition).Error; err != nil || definition == "" {
			return errors.New("tenant migration: check readiness failed")
		}
		if normalizeMigrationCheckDefinition(definition) != normalizeMigrationCheckDefinition("(`default_locale_key` IN ('zh-cn', 'en-us'))") {
			return errors.New("tenant migration: check shape readiness failed")
		}
	default:
		return errors.New("tenant migration: unsupported check dialect")
	}
	return nil
}

func normalizeMigrationSQL(value string) string {
	return strings.Join(strings.Fields(strings.ToLower(value)), " ")
}

var migrationCharsetIntroducer = regexp.MustCompile(`_[a-z0-9]+(')`)

func normalizeMigrationCheckDefinition(value string) string {
	value = strings.ToLower(value)
	value = strings.ReplaceAll(value, "\\'", "'")
	value = migrationCharsetIntroducer.ReplaceAllString(value, "$1")
	return strings.NewReplacer(
		" ", "",
		"\t", "",
		"\r", "",
		"\n", "",
		"`", "",
		"\"", "",
	).Replace(value)
}
