// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/response/actions"

// Tenant is the persistent entity generated for 租户.
type Tenant struct {
	actions.ModelGorm
	DisplayName      string `json:"displayName" gorm:"column:display_name;type:varchar(200);not null;comment:租户名称"`
	Slug             string `json:"slug" gorm:"column:slug;type:varchar(63);not null;uniqueIndex:ux_biz_tenants_slug;comment:租户标识"`
	DesiredServing   bool   `json:"desiredServing" gorm:"column:desired_serving;type:boolean;not null;default:true;comment:期望对外服务"`
	H5Host           string `json:"h5Host" gorm:"column:h5_host;type:varchar(253);not null;uniqueIndex:ux_biz_tenants_h5_host;comment:H5 域名"`
	WechatAppID      string `json:"wechatAppId" gorm:"column:wechat_app_id;type:varchar(64);comment:微信 AppID"`
	DefaultLocaleKey string `json:"defaultLocaleKey" gorm:"column:default_locale_key;type:varchar(255);not null;default:zh-cn;comment:默认语言"`
	DefaultCurrency  string `json:"defaultCurrency" gorm:"column:default_currency;type:varchar(3);not null;comment:默认货币"`
	TimeZone         string `json:"timeZone" gorm:"column:time_zone;type:varchar(64);not null;comment:时区"`
}

// TableName returns the stable database table name.
func (*Tenant) TableName() string {
	return "biz_tenants"
}
