// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"errors"
	"testing"

	"github.com/mss-boot-io/mss-boot-admin/admin/business"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	"gorm.io/gorm"
)

func TestTenantTableName(t *testing.T) {
	if got, want := new(Tenant).TableName(), "biz_tenants"; got != want {
		t.Fatalf("TableName() = %q, want %q", got, want)
	}
}

func TestTenantMigrationIdentityIsComplete(t *testing.T) {
	if got, want := TenantMigrationID.String(), "66966149766766"; got != want {
		t.Fatalf("migration ID = %q, want %q", got, want)
	}
}

func TestTenantAuthorizationMigrationIdentityIsComplete(t *testing.T) {
	if got, want := TenantAuthorizationMigrationID.String(), "66966149766767"; got != want {
		t.Fatalf("authorization migration ID = %q, want %q", got, want)
	}
}

func TestTenantPermissionCodesAreUnique(t *testing.T) {
	codes := []string{
		"tenant:create",
		"tenant:delete",
		"tenant:export",
		"tenant:list",
		"tenant:read",
		"tenant:update",
	}
	seen := make(map[string]struct{}, len(codes))
	for _, code := range codes {
		if _, exists := seen[code]; exists {
			t.Fatalf("duplicate permission code %q", code)
		}
		seen[code] = struct{}{}
	}
}

func TestTenantOperationContractMatchesSpecification(t *testing.T) {
	contracts := OperationContracts()
	if got, want := len(contracts), 6; got != want {
		t.Fatalf("operation contracts = %d, want %d", got, want)
	}
	want := map[string]string{
		"POST /admin/api/tenants":        PermissionCreate,
		"DELETE /admin/api/tenants/{id}": PermissionDelete,
		"GET /admin/api/tenants/export":  PermissionExport,
		"GET /admin/api/tenants/{id}":    PermissionRead,
		"GET /admin/api/tenants":         PermissionList,
		"PUT /admin/api/tenants/{id}":    PermissionUpdate,
	}
	for _, contract := range contracts {
		key := contract.Method + " " + contract.Path
		if permission, exists := want[key]; !exists || permission != contract.Permission {
			t.Fatalf("unexpected operation contract %#v", contract)
		}
		delete(want, key)
	}
	if len(want) != 0 {
		t.Fatalf("missing operation contracts: %#v", want)
	}
}

func TestTenantDescriptorProjectsAuthorizationMetadataWithoutInferringComposition(t *testing.T) {
	module := Module()
	if got, want := module.Name(), "tenant"; got != want {
		t.Fatalf("Module().Name() = %q, want %q", got, want)
	}
	registry, err := business.Compose(migration.New(), module)
	if err != nil {
		t.Fatalf("compose generated module: %v", err)
	}
	descriptors := registry.Descriptors()
	if len(descriptors) != 1 {
		t.Fatalf("generated descriptors = %#v", descriptors)
	}
	descriptor := descriptors[0]
	if descriptor.Migrate != nil {
		t.Fatal("generated descriptor must not expose AutoMigrate or another inferred migration hook")
	}
	if got, want := len(descriptor.Permissions), 6; got != want {
		t.Fatalf("descriptor permissions = %d, want %d", got, want)
	}
	if got, want := descriptor.Menu.Path, "/tenants"; got != want {
		t.Fatalf("descriptor menu path = %q, want %q", got, want)
	}
	runner, err := registry.MigrationRunner()
	if err != nil {
		t.Fatalf("clone generated migration runner: %v", err)
	}
	if err := runner.Register(TenantMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated schema migration was not registered: %v", err)
	}
	if err := runner.Register(TenantAuthorizationMigrationID, func(*gorm.DB, string) error { return nil }); !errors.Is(err, migration.ErrDuplicateMigrationID) {
		t.Fatalf("generated authorization migration was not registered: %v", err)
	}
}
