// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"context"
	"errors"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"github.com/glebarez/sqlite"
	"github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration"
	migrationmodels "github.com/mss-boot-io/mss-boot-admin/mss-boot/pkg/migration/models"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

type collectingTenantEvents struct {
	mu        sync.Mutex
	db        *gorm.DB
	events    []DomainEvent
	committed []bool
}

func (collector *collectingTenantEvents) Collect(_ context.Context, event DomainEvent) {
	var count int64
	resourceID := ""
	switch typed := event.(type) {
	case TenantCreatedEvent:
		resourceID = typed.ResourceID
	case TenantUpdatedEvent:
		resourceID = typed.ResourceID
	}
	committed := collector.db.Model(new(Tenant)).Where("id = ?", resourceID).Count(&count).Error == nil && count == 1
	collector.mu.Lock()
	defer collector.mu.Unlock()
	collector.events = append(collector.events, event)
	collector.committed = append(collector.committed, committed)
}

func (collector *collectingTenantEvents) snapshot() ([]DomainEvent, []bool) {
	collector.mu.Lock()
	defer collector.mu.Unlock()
	return append([]DomainEvent(nil), collector.events...), append([]bool(nil), collector.committed...)
}

func TestTenantServiceCRUDQueryExportAndPostCommitEvents(t *testing.T) {
	db := openTenantTestDatabase(t)
	if _, err := NewService(db, nil); err == nil {
		t.Fatal("NewService(nil event collector) unexpectedly succeeded")
	}
	var typedNilCollector *collectingTenantEvents
	if _, err := NewService(db, typedNilCollector); err == nil {
		t.Fatal("NewService(typed nil event collector) unexpectedly succeeded")
	}
	collector := &collectingTenantEvents{db: db}
	service, err := NewService(db, collector)
	if err != nil {
		t.Fatalf("NewService() error = %v", err)
	}

	invalid := validTenantInput()
	invalid.Slug = "invalid value"
	if _, err := service.Create(context.Background(), invalid); err == nil {
		t.Fatal("Create(invalid pattern) unexpectedly succeeded")
	}
	invalid.DefaultCurrency = "invalid value"
	if _, err := service.Create(context.Background(), invalid); err == nil {
		t.Fatal("Create(invalid pattern) unexpectedly succeeded")
	}

	input := validTenantInput()
	created, err := service.Create(context.Background(), input)
	if err != nil {
		t.Fatalf("Create() error = %v", err)
	}
	if created.ID == "" {
		t.Fatal("Create() did not assign an ID")
	}
	if created.DesiredServing != true {
		t.Fatalf("default desiredServing = %v", created.DesiredServing)
	}
	if created.DefaultLocaleKey != "zh-cn" {
		t.Fatalf("default defaultLocaleKey = %q", created.DefaultLocaleKey)
	}
	events, committed := collector.snapshot()
	if len(events) != 1 || events[0].EventName() != "platform.tenant.created" || !committed[0] {
		t.Fatalf("created events = %#v, committed = %#v", events, committed)
	}
	if _, err := service.Create(context.Background(), validTenantInput()); !errors.Is(err, ErrTenantConflict) {
		t.Fatalf("Create(duplicate) error = %v, want conflict", err)
	}

	secondInput := validTenantInput()
	secondInput.DisplayName = "VALUE_02"
	secondInput.Slug = "alternate"
	secondInput.H5Host = "VALUE_02"
	secondInput.WechatAppID = "VALUE_02"
	secondInput.DefaultCurrency = "VAL"
	secondInput.TimeZone = "VALUE_02"
	second, err := service.Create(context.Background(), secondInput)
	if err != nil {
		t.Fatalf("Create(second) error = %v", err)
	}
	if err := db.Exec("CREATE UNIQUE INDEX ux_tenant_generated_update_conflict ON biz_tenants (display_name)").Error; err != nil {
		t.Fatalf("create update conflict index: %v", err)
	}
	conflictingValue := second.DisplayName
	if _, err := service.Update(context.Background(), created.ID, &UpdateTenantInput{DisplayName: &conflictingValue}); !errors.Is(err, ErrTenantConflict) {
		t.Fatalf("Update(duplicate without TranslateError) error = %v, want conflict", err)
	}
	if err := db.Exec("DROP INDEX ux_tenant_generated_update_conflict").Error; err != nil {
		t.Fatalf("drop update conflict index: %v", err)
	}
	conflictingUniqueValue := second.Slug
	if _, err := service.Update(context.Background(), created.ID, &UpdateTenantInput{Slug: &conflictingUniqueValue}); !errors.Is(err, ErrTenantConflict) {
		t.Fatalf("Update(declared duplicate without TranslateError) error = %v, want conflict", err)
	}

	query := ListTenantQuery{
		Current:          1,
		PageSize:         1,
		SortBy:           "displayName",
		SortOrder:        "asc",
		Q:                input.DisplayName,
		DesiredServing:   input.DesiredServing,
		DefaultLocaleKey: input.DefaultLocaleKey,
	}
	page, err := service.List(context.Background(), query)
	if err != nil {
		t.Fatalf("List() error = %v", err)
	}
	if page.Total != 1 || len(page.Data) != 1 || page.Data[0].ID != created.ID {
		t.Fatalf("List() = %#v", page)
	}
	updatedValue := "VALUE_02"
	updated, err := service.Update(context.Background(), created.ID, &UpdateTenantInput{DisplayName: &updatedValue})
	if err != nil {
		t.Fatalf("Update() error = %v", err)
	}
	if updated.DisplayName != updatedValue {
		t.Fatalf("updated displayName = %q", updated.DisplayName)
	}
	events, committed = collector.snapshot()
	if events[len(events)-1].EventName() != "platform.tenant.updated" || !committed[len(committed)-1] {
		t.Fatalf("updated events = %#v, committed = %#v", events, committed)
	}

	var exported strings.Builder
	if err := service.Export(context.Background(), ListTenantQuery{}, &exported); err != nil {
		t.Fatalf("Export() error = %v", err)
	}
	if !strings.Contains(exported.String(), "id,") || !strings.Contains(exported.String(), created.ID) {
		t.Fatalf("Export() = %q", exported.String())
	}
	if got := csvSafe("=SUM(A1:A2)"); got != "'=SUM(A1:A2)" {
		t.Fatalf("csvSafe() = %q", got)
	}

	if err := service.Delete(context.Background(), second.ID); err != nil {
		t.Fatalf("Delete() error = %v", err)
	}
	if _, err := service.Get(context.Background(), second.ID); !errors.Is(err, ErrTenantNotFound) {
		t.Fatalf("Get(deleted) error = %v, want not found", err)
	}
}

func validTenantInput() *CreateTenantInput {
	return &CreateTenantInput{
		DisplayName:     "VALUE_01",
		Slug:            "value",
		H5Host:          "VALUE_01",
		WechatAppID:     "VALUE_01",
		DefaultCurrency: "VAL",
		TimeZone:        "VALUE_01",
	}
}

func testBool(value bool) *bool { return &value }

func openTenantTestDatabase(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(filepath.Join(t.TempDir(), "tenant.db")), &gorm.Config{
		TranslateError: false,
		Logger:         logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open sqlite: %v", err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		t.Fatalf("database handle: %v", err)
	}
	t.Cleanup(func() { _ = sqlDB.Close() })
	if err := db.Exec("CREATE TABLE mss_boot_migration (version TEXT PRIMARY KEY, apply_time DATETIME NOT NULL)").Error; err != nil {
		t.Fatalf("create migration table: %v", err)
	}
	prepareTenantAuthorizationTestSchema(t, db)
	runner := migration.New()
	if err := RegisterMigration(runner); err != nil {
		t.Fatalf("RegisterMigration() error = %v", err)
	}
	runner.SetDb(db)
	runner.SetModel(new(migrationmodels.Migration))
	if err := runner.MigrateContext(context.Background()); err != nil {
		t.Fatalf("MigrateContext() error = %v", err)
	}
	return db
}
