// Code generated by mss module template 1.3.0-backend.2 from .mss/modules/tenant.yaml. DO NOT EDIT.

package tenant

import (
	"context"
	"encoding/csv"
	"errors"
	"fmt"
	"io"
	"reflect"
	"sort"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

const maxTenantExportRows = 10000

var (
	ErrTenantNotFound    = errors.New("tenant not found")
	ErrTenantConflict    = errors.New("tenant conflict")
	ErrTenantPersistence = errors.New("tenant persistence unavailable")
	ErrTenantExportLimit = errors.New("tenant export limit exceeded")
)

// Application is the generated backend use-case boundary consumed by HTTP.
type Application interface {
	List(context.Context, ListTenantQuery) (TenantPage, error)
	Get(context.Context, string) (*Tenant, error)
	Create(context.Context, *CreateTenantInput) (*Tenant, error)
	Update(context.Context, string, *UpdateTenantInput) (*Tenant, error)
	Delete(context.Context, string) error
	Export(context.Context, ListTenantQuery, io.Writer) error
}

// Service owns authoritative tenant transactions.
type Service struct {
	db     *gorm.DB
	events EventCollector
}

func NewService(db *gorm.DB, events EventCollector) (*Service, error) {
	if db == nil {
		return nil, errors.New("tenant database is required")
	}
	if isNilEventCollector(events) {
		return nil, errors.New("tenant event collector is required")
	}
	return &Service{db: db, events: events}, nil
}

func isNilEventCollector(events EventCollector) bool {
	if events == nil {
		return true
	}
	value := reflect.ValueOf(events)
	switch value.Kind() {
	case reflect.Chan, reflect.Func, reflect.Interface, reflect.Map, reflect.Pointer, reflect.Slice:
		return value.IsNil()
	default:
		return false
	}
}

func (service *Service) List(ctx context.Context, query ListTenantQuery) (TenantPage, error) {
	if service == nil || service.db == nil {
		return TenantPage{}, ErrTenantPersistence
	}
	if ctx == nil {
		return TenantPage{}, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := query.normalizeAndValidate(); err != nil {
		return TenantPage{}, err
	}
	db := applyTenantQuery(service.db.WithContext(ctx).Model(new(Tenant)), query)
	var total int64
	if err := db.Count(&total).Error; err != nil {
		return TenantPage{}, normalizeTenantDBError(err)
	}
	var records []Tenant
	db = orderTenantQuery(db, query)
	if err := db.Offset((query.Current - 1) * query.PageSize).Limit(query.PageSize).Find(&records).Error; err != nil {
		return TenantPage{}, normalizeTenantDBError(err)
	}
	return TenantPage{Data: records, Total: total, Current: query.Current, PageSize: query.PageSize}, nil
}

func (service *Service) Get(ctx context.Context, id string) (*Tenant, error) {
	if service == nil || service.db == nil {
		return nil, ErrTenantPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	var record Tenant
	if err := service.db.WithContext(ctx).First(&record, "id = ?", id).Error; err != nil {
		return nil, normalizeTenantDBError(err)
	}
	return &record, nil
}

func (service *Service) Create(ctx context.Context, input *CreateTenantInput) (*Tenant, error) {
	if service == nil || service.db == nil {
		return nil, ErrTenantPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	record := &Tenant{
		DisplayName:      input.DisplayName,
		Slug:             input.Slug,
		DesiredServing:   boolValue(input.DesiredServing),
		H5Host:           input.H5Host,
		WechatAppID:      input.WechatAppID,
		DefaultLocaleKey: input.DefaultLocaleKey,
		DefaultCurrency:  input.DefaultCurrency,
		TimeZone:         input.TimeZone,
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		return tx.Create(record).Error
	}); err != nil {
		return nil, service.normalizeTenantWriteError(ctx, "", record, err)
	}
	service.events.Collect(ctx, TenantCreatedEvent{ResourceID: record.ID, OccurredAt: record.CreatedAt})
	return record, nil
}

func (service *Service) Update(ctx context.Context, id string, input *UpdateTenantInput) (*Tenant, error) {
	if service == nil || service.db == nil {
		return nil, ErrTenantPersistence
	}
	if ctx == nil {
		return nil, &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, &ValidationError{Field: "id", Rule: "required"}
	}
	if err := input.normalizeAndValidate(); err != nil {
		return nil, err
	}
	changedFields := make([]string, 0, 8)
	updates := make(map[string]any, 8)
	if input.DisplayName != nil {
		updates["display_name"] = *input.DisplayName
		changedFields = append(changedFields, "displayName")
	}
	if input.Slug != nil {
		updates["slug"] = *input.Slug
		changedFields = append(changedFields, "slug")
	}
	if input.DesiredServing != nil {
		updates["desired_serving"] = *input.DesiredServing
		changedFields = append(changedFields, "desiredServing")
	}
	if input.H5Host != nil {
		updates["h5_host"] = *input.H5Host
		changedFields = append(changedFields, "h5Host")
	}
	if input.WechatAppID != nil {
		updates["wechat_app_id"] = *input.WechatAppID
		changedFields = append(changedFields, "wechatAppId")
	}
	if input.DefaultLocaleKey != nil {
		updates["default_locale_key"] = *input.DefaultLocaleKey
		changedFields = append(changedFields, "defaultLocaleKey")
	}
	if input.DefaultCurrency != nil {
		updates["default_currency"] = *input.DefaultCurrency
		changedFields = append(changedFields, "defaultCurrency")
	}
	if input.TimeZone != nil {
		updates["time_zone"] = *input.TimeZone
		changedFields = append(changedFields, "timeZone")
	}
	sort.Strings(changedFields)
	var record Tenant
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		if input.DisplayName != nil {
			record.DisplayName = *input.DisplayName
		}
		if input.Slug != nil {
			record.Slug = *input.Slug
		}
		if input.DesiredServing != nil {
			record.DesiredServing = *input.DesiredServing
		}
		if input.H5Host != nil {
			record.H5Host = *input.H5Host
		}
		if input.WechatAppID != nil {
			record.WechatAppID = *input.WechatAppID
		}
		if input.DefaultLocaleKey != nil {
			record.DefaultLocaleKey = *input.DefaultLocaleKey
		}
		if input.DefaultCurrency != nil {
			record.DefaultCurrency = *input.DefaultCurrency
		}
		if input.TimeZone != nil {
			record.TimeZone = *input.TimeZone
		}
		if err := tx.Model(&record).Updates(updates).Error; err != nil {
			return err
		}
		return tx.First(&record, "id = ?", id).Error
	}); err != nil {
		return nil, service.normalizeTenantWriteError(ctx, id, &record, err)
	}
	service.events.Collect(ctx, TenantUpdatedEvent{ResourceID: record.ID, ChangedFields: changedFields, OccurredAt: record.UpdatedAt})
	return &record, nil
}

func (service *Service) Delete(ctx context.Context, id string) error {
	if service == nil || service.db == nil {
		return ErrTenantPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return &ValidationError{Field: "id", Rule: "required"}
	}
	if err := service.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		var record Tenant
		if err := tx.Clauses(clause.Locking{Strength: "UPDATE"}).First(&record, "id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&record).Error
	}); err != nil {
		return normalizeTenantDBError(err)
	}
	return nil
}

func (service *Service) Export(ctx context.Context, query ListTenantQuery, destination io.Writer) error {
	if service == nil || service.db == nil {
		return ErrTenantPersistence
	}
	if ctx == nil {
		return &ValidationError{Field: "context", Rule: "required"}
	}
	if destination == nil {
		return &ValidationError{Field: "destination", Rule: "required"}
	}
	query.Current = 1
	query.PageSize = 100
	if err := query.normalizeAndValidate(); err != nil {
		return err
	}
	var records []Tenant
	db := applyTenantQuery(service.db.WithContext(ctx).Model(new(Tenant)), query)
	db = orderTenantQuery(db, query).Limit(maxTenantExportRows + 1)
	if err := db.Find(&records).Error; err != nil {
		return normalizeTenantDBError(err)
	}
	if len(records) > maxTenantExportRows {
		return ErrTenantExportLimit
	}
	writer := csv.NewWriter(destination)
	if err := writer.Write([]string{"id", "displayName", "slug", "desiredServing", "h5Host", "wechatAppId", "defaultLocaleKey", "defaultCurrency", "timeZone"}); err != nil {
		return ErrTenantPersistence
	}
	for _, record := range records {
		row := []string{csvSafe(record.ID), csvSafe(fmt.Sprint(record.DisplayName)), csvSafe(fmt.Sprint(record.Slug)), csvSafe(fmt.Sprint(record.DesiredServing)), csvSafe(fmt.Sprint(record.H5Host)), csvSafe(fmt.Sprint(record.WechatAppID)), csvSafe(fmt.Sprint(record.DefaultLocaleKey)), csvSafe(fmt.Sprint(record.DefaultCurrency)), csvSafe(fmt.Sprint(record.TimeZone))}
		if err := writer.Write(row); err != nil {
			return ErrTenantPersistence
		}
	}
	writer.Flush()
	if writer.Error() != nil {
		return ErrTenantPersistence
	}
	return nil
}

func applyTenantQuery(db *gorm.DB, query ListTenantQuery) *gorm.DB {
	if query.Q != "" {
		pattern := "%" + escapeLike(strings.ToLower(query.Q)) + "%"
		db = db.Where(
			strings.Join([]string{
				"LOWER(display_name) LIKE ? ESCAPE '!'",
				"LOWER(slug) LIKE ? ESCAPE '!'",
				"LOWER(h5_host) LIKE ? ESCAPE '!'",
				"LOWER(wechat_app_id) LIKE ? ESCAPE '!'",
			}, " OR "),
			pattern,
			pattern,
			pattern,
			pattern,
		)
	}
	if query.DesiredServing != nil {
		db = db.Where("desired_serving = ?", *query.DesiredServing)
	}
	if query.DefaultLocaleKey != "" {
		db = db.Where("default_locale_key = ?", query.DefaultLocaleKey)
	}
	return db
}

func orderTenantQuery(db *gorm.DB, query ListTenantQuery) *gorm.DB {
	columns := map[string]string{
		"displayName": "display_name",
		"slug":        "slug",
	}
	if column := columns[query.SortBy]; column != "" {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: column}, Desc: query.SortOrder == "desc"})
	} else {
		db = db.Order(clause.OrderByColumn{Column: clause.Column{Name: "created_at"}, Desc: true})
	}
	return db.Order(clause.OrderByColumn{Column: clause.Column{Name: "id"}})
}

func normalizeTenantDBError(err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, gorm.ErrRecordNotFound):
		return ErrTenantNotFound
	case errors.Is(err, gorm.ErrDuplicatedKey), isUniqueConstraintError(err):
		return ErrTenantConflict
	case errors.Is(err, context.Canceled), errors.Is(err, context.DeadlineExceeded):
		return err
	default:
		return ErrTenantPersistence
	}
}

func isUniqueConstraintError(err error) bool {
	type sqlStateError interface {
		SQLState() string
	}
	var sqlState sqlStateError
	if errors.As(err, &sqlState) && sqlState.SQLState() == "23505" {
		return true
	}
	type sqliteCodeError interface {
		Code() int
	}
	var sqliteCode sqliteCodeError
	if errors.As(err, &sqliteCode) && (sqliteCode.Code() == 1555 || sqliteCode.Code() == 2067) {
		return true
	}
	for current := err; current != nil; current = errors.Unwrap(current) {
		value := reflect.ValueOf(current)
		if value.Kind() == reflect.Pointer && !value.IsNil() {
			value = value.Elem()
		}
		if value.Kind() != reflect.Struct {
			continue
		}
		number := value.FieldByName("Number")
		if number.IsValid() && number.CanUint() && number.Kind() >= reflect.Uint && number.Kind() <= reflect.Uint64 && number.Uint() == 1062 {
			return true
		}
	}
	return false
}
func (service *Service) normalizeTenantWriteError(ctx context.Context, excludeID string, record *Tenant, err error) error {
	normalized := normalizeTenantDBError(err)
	if !errors.Is(normalized, ErrTenantPersistence) {
		return normalized
	}
	conflict, probeErr := service.hasTenantUniqueConflict(ctx, excludeID, record)
	if probeErr != nil {
		return ErrTenantPersistence
	}
	if conflict {
		return ErrTenantConflict
	}
	return normalized
}

func (service *Service) hasTenantUniqueConflict(ctx context.Context, excludeID string, record *Tenant) (bool, error) {
	if record == nil {
		return false, nil
	}
	query0 := service.db.WithContext(ctx).Unscoped().Model(new(Tenant))
	query0 = query0.Where("h5_host = ?", record.H5Host)
	if excludeID != "" {
		query0 = query0.Where("id <> ?", excludeID)
	}
	var count0 int64
	if err := query0.Count(&count0).Error; err != nil {
		return false, err
	}
	if count0 > 0 {
		return true, nil
	}
	query1 := service.db.WithContext(ctx).Unscoped().Model(new(Tenant))
	query1 = query1.Where("slug = ?", record.Slug)
	if excludeID != "" {
		query1 = query1.Where("id <> ?", excludeID)
	}
	var count1 int64
	if err := query1.Count(&count1).Error; err != nil {
		return false, err
	}
	if count1 > 0 {
		return true, nil
	}
	return false, nil
}

func boolValue(value *bool) bool {
	return value != nil && *value
}

func escapeLike(value string) string {
	value = strings.ReplaceAll(value, `!`, `!!`)
	value = strings.ReplaceAll(value, `%`, `!%`)
	return strings.ReplaceAll(value, `_`, `!_`)
}

func csvSafe(value string) string {
	if value == "" {
		return value
	}
	switch value[0] {
	case '=', '+', '-', '@':
		return "'" + value
	default:
		return value
	}
}
